In [1]:
import pandas as pd
import PyPDF2
import os
import seaborn as sns
import openai
import matplotlib.pyplot as plt
import numpy as np
import re
from textstat import flesch_reading_ease
import requests
import json
import pandas as pd
import prettytable
import zipfile
import difflib
from difflib import get_close_matches
from sklearn.preprocessing import OneHotEncoder
from scipy.stats import entropy
import pyarrow.parquet as pq

In [2]:
### DataFrame and Graphs Settings
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colum', None)
pd.set_option("display.max_colwidth", None)

sns.set(font_scale=1.5)
sns.set(style='white', font_scale=1.5)

## Main

In [3]:
df= pd.read_parquet('/Users/mgor/Dropbox/Second YPP/Data/Data Aux/compustat_database.parquet')

In [4]:
df.head()

,gvkey,tic,cusip,comCounty,comDom,comCountry,comNAICS,comHeadquarters,OccFam,OccFamName,SOC,SOCName,CanonEmployer,Sector,SectorName,NAICS3,NAICS4,NAICS5,NAICS6,State,County,FIPSState,FIPSCounty,FIPS,BestFitMSA,BestFitMSAName,Year,qtr,Degree,Exp,boncom,parttime,NoWage,MeanWage,VarRange,hires_nt,jobOpenings_nt,layoffs_nt,otherSeparations_nt,quits_nt,totalSeparations_nt,unemployedPerOpening_nt,hires_st,jobOpenings_st,layoffs_st,quits_st,totalSeparations_st,unemployedPerOpening_st,tot_emp,emp_prse,jobs_1000,natEmp,a_mean_nt,SOCShare,0507SOCShare,shiftSOC,wkWageNAICS,shiftNAICS,07LNAICSShare,BShareimq,BShareHK,DivIntRent,UIC,earnWork,emplGovContr,emplPensionContr,farmPropInc,incManBen,netEarnbyRes,nonfarmPropInc,pInc,pTransReceipt,percapDivRent,percapEarn,percapInc,percapIncMan,percapRet,percapTrans,percapUIC,pop,propInc,retirement,supplWages,wages,lgdp_change,igdpq_ch,crisis_ch,lpctunion,pctunion_ind,pctunion_occ,employment_st,laborForce_st,unemployment_st,unemploymentRate_st,laborForce_msa,employment_msa,unemployment_msa,unemploymentRate_msa,employment_ct,laborForce_ct,unemployment_ct,unemploymentRate_ct,MSAopenings_employer,FIPSopenings_employer,MSAOccopenings_employer,FIPSOccopenings_employer,MSASectoropenings_employer,FIPSSectoropenings_employer,TopQuartileMSAopenings,TopQuartileFIPSopenings,TopQuartileMSAOccopenings,TopQuartileFIPSOccopenings,TopQuartileMSASectoropenings,TopQuartileFIPSSectoropenings,tight,vacan,tightocc,vacanocc,tightsector,vacansector,Male,Female,white,black,americanIndian,alaskaNative,asian,hawaiianPacificIslander,someOtherRace,ageMean,pop_msa,white_msa,black_msa,americanIndianAlaskaNative_msa,asian_msa,nativeHawaiianPacificIslander_msa,someOtherRace_msa,kcosts,kprod,kshare,ktolb,hworked,lcomp,lprod,lshare,opw,routput,tfp,ulc,intmig,dommig,college_st,nonprofit,quarter,roa,roe,logSize,gProfit,tobinq,lev,comAge,IsSpecialized,IsBaseline,IsSoftware,Administration,agricultureHorticulture,Analysis,architectureConstruction,Business,customerClient,Design,economicsPolicy,educationTraining,energyUtilities,Engineering,Environment,Finance,healthCare,humanResources,industryKnowledge,informationTechnology,Legal,maintenanceRepair,manufacturingProduction,marketingPublic,mediaWriting,personalCare,publicSafety,Religion,Sales,scienceResearch,supplyChain,notMapped,SkillsCount,SkillClusterCount,SkillClusterbyFam,SkillFamilyCount,ClusterToFamilyRatio,SkillFamilyCoverage,SkillFamilyEntropy,pecuniary_benefits_count,job_design_characteristics_count,career_development_opportunities_count,organizational_culture_count,meaningful_work_count,environmental_initiatives_count,social_initiatives_count,job_tasks_requirements_count,main_count,length,sr_count,pecuniary_benefits_prop,job_design_characteristics_prop,career_development_opportunities_prop,organizational_culture_prop,meaningful_work_prop,environmental_initiatives_prop,social_initiatives_prop,job_tasks_requirements_prop,main_prop,sr_prop,opEmptot_count,bartik,sr_jobs,main_jobs,sr_ind,main_ind
0,10005.0,SRCTQ,853887206,None,D,USA,323111,OH,11,Management Occupations,11-2022,Sales Managers,Standard Register,54,"Professional, Scientific, and Technical Services",-999,-999,-999,-999,Ohio,Montgomery,39,113,39113,19380,"Dayton, OH",2010,1,1.0,8.0,0.0,0.0,1.0,NaN,NaN,3.3,2.0,1.5,0.2,1.4,3.1,5.7,2.8,1.9,1.5,1.3,3.0,6.5,790.0,11.1,2.191,319300.0,114110.0,0.002231,0.001551,-0.020082,1176.0,-0.037028,0.000000,-0.000103,-0.004842,-1.493404,-4.496601,1.009402,-0.970814,3.426168,5.405997,8.991433,1.031472,8.879074,1.857545,6.505426,-1.577592,0.949260,1.770415,8.955224,6.825490,6.416065,-4.625551,0.084440,8.859660,6.918872,2.009323,0.174402,-0.002065,NaN,NaN,0.072964,0.017361,0.009060,5259913.0,5904597.0,644684.0,10.9,12.912933,12.788313,10.768780,11.7,12.363196,12.495378,10.406442,12.4,1.386294,1.386294,0.693147,0.693147,1.098612,1.098612,0.0,0.0,0.0,0.0,0.0,0.0,-5.309194,-7.453347,-6.625645,-8.769798,-6.680006,-8.824159,55.582865,44.417135,94.279611,2.999181,0.000000,0.0,1.629799,0.000000,0.266269,44.0,841310.0,79.942708,15.028468,0.130511,1.871248,0.004160,0.766543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000457,-0.000334,23.1,NaN,1.0,-0.220062,-1.846636,5.911994,35.655794,0.519686,0.097179,NaN,0.687500,0.312500,0.250000,0.0625,0.0,0.0,0.0,0.250000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.312500,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.375000,16.0,8.0,2.187500,4.0,0.546875,0.137931,1.251156,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,573.0,0.0,0.00000,0.00000,0.000000,0.000000,0.0,0.0,0.0,1.000000,0.000000,0.0,1.0,0.000004,0.0,0.0,0,0
1,10005.0,SRCTQ,853887206,None,D,USA,323111,OH,11,Management Occupations,11-3031,Financial Managers,Standard Register,61,Educational Services,611,6112,-999,-999,California,Sacramento,6,67,6067,40900,"Sacramento--Roseville--Arden-Arcade, CA",2010,1,1.0,6.0,0.0,0.0,1.0,NaN,NaN,3.3,2.0,1.5,0.2,1.4,3.1,5.7,2.7,2.3,1.3,1.2,2.9,6.8,3900.0,4.6,4.760,478940.0,116970.0,0.003291,0.004113,-0.015407,630.0,0.007613,0.007929,0.000383,-0.008175,-2.336278,21.534724,-0.131751,-2.115065,3.184049,-28.802227,5.690869,0.070261,4.598257,1.983132,12.069942,-3.262726,-0.870126,1.023963,4.696673,11.250663,11.020238,20.370370,0.948743,3.808197,12.318650,1.980189,-1.156433,0.036977,NaN,NaN,0.244994,0.140091,0.024596,16050996.0,18359589.0,2308593.0,12.6,13.866935,13.731131,11.803264,12.7,13.298519,13.440322,11.416943,13.2,0.693147,0.693147,0.000000,0.000000,0.693147,0.693147,0.0,0.0,0.0,0.0,0.0,0.0,-4.692976,-6.756647,-5.889761,-7.953432,-7.053993,-9.117665,44.203617,55.796383,66.410720,5.468188,0.250763,0.0,18.269411,0.609736,6.487439,43.0,2154391.0,67.237980,7.191499,1.013094,11.856112,0.768802,6.208344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000451,0.000178,27.1,NaN,1.0,-0.220062,-1.846636,5.911994,35.655794,0.519686,0.097179,NaN,0.722222,0.277778,0.111111,0.0000,0.0,0.0,0.0,0.111111,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.333333,0.0,0.000000,0.0,0.055556,0.0,0.0,0.055556,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.166667,0.277778,18.0,10.0,2.166667,6.0,0.361111,0.206897,1.585934,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,538.0,0.0,0.00000,0.00000,0.000000,0.037037,0.0,0.0,0.0,0.962963,0.037037,0.0,1.0,0.000003,0.0,0.0,0,0
2,10005.0,SRCTQ,853887206,None,D,USA,323111,OH,11,Management Occupations,11-3051,Industrial Production Managers,Standard Register,61,Educational Services,611,6112,-999,-999,Maryland,Wicomico,24,45,24045,41540,"Salisbury, MD-DE",2010,1,1.0,4.0,0.0,0.0,1.0,NaN,NaN,3.3,2.0,1.5,0.2,1.4,3.1,5.7,3.8,2.2,1.2,1.7,3.0,4.4,40.0,12.3,0.709,143310.0,95660.0,0.001189,0.000751,-0.002524,0.0,0.004101,0.000000,0.000000,-0.003311,-2.767250,4.485633,1.717361,5.482332,1.359466,-8.421425,10.356262,1.988122,24.544499,2.789412,8.814317,-3.641509,1.066391,1.855918,9.457755,7.907049,7.820935,3.598972,0.913642,18.512443,8.886094,2.522082,-0.099274,0.052040,NaN,NaN,0.114964,0.140091,0.016044,2818977.0,3064844.0,245867.0,8.0,12.080192,11.970660,9.814383,10.4,10.662376,10.782388,8.602820,11.3,0.693147,0.693147,0.000000,0.000000,0.693147,0.693147,0.0,0.0,0.0,0.0,0.0,0.0,-5.464105,-7.729914,-6.595507,-8.861316,-8.715771,-10.981580,86.289276,13.710724,88.730200,7.945988,0.000000,0.0,3.323812,0.000000,0.000000,47.0,125324.0,65.249274,27.815103,1.259934,2.290862,0.000000,1.185727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000582,0.001603,26.0,NaN,1.0,-0.220062,-1.846636,5.911994,35.655794,0.519686,0.097179,NaN,0.846154,0.153846,0.153846,0.0000,0.0,0.0,0.0,0.153846,0.076923,0.0,0.0,0.0,0.0,0.0,0.0,0.076923,0.0,0.000000,0.0,0.076923,0.0,0.0,0.461538,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.153846,13.0,8.0,1.615385,6.0,0.269231,0.206897,1.524707,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,295.0,0.0,0.00000,0.00000,0.000000,0.055556,0.0,0.0,0.0,0.944444,0.000000,0.0,1.0,0.000000,0.0,0.0,0,0
3,10005.0,SRCTQ,853887206,None,D,USA,323111,OH,11,Management Occupations,11-3051,Industrial Production Managers,Standard Register,61,Educational Services,611,6112,-999,-999,Pennsylvania,York,42,133,42133,49620,"York-Hanover, PA",2010,1,1.0,2.0,0.0,0.0,1.0,NaN,NaN,3.3,2.0,1.5,0.2,1.4,3.1,5.7,3.2,2.4,1.9,1.4,3.4,3.9,300.0,8.6,1.776,143310.0,95660.0,0.001065,0.002070,-0.012439,709.0,0.008235,0.004845,0.000224,-0.008308,-1.834559,-1.015694,1.511324,4.078129,3.906452,25.997699,16.857030,0.312958,-5.851504,1.378240,8.369844,-2.411253,-0.273254,0.785723,16.283925,8.071749,7.738955,-1.540832,0.587499,-5.616559,8.719587,3.955241,2.362719,0.078969,NaN,NaN,0.139600,0.140091,0.016044,5820638.0,6359683.0,539045.0,8.5,12.340726,12.255363,9.837508,8.2,12.243296,12.336759,9.920197,8.9,0.693147,0.693147,0.000000,0.000000,0.693147,0.693147,0.0,0.0,0.0,0.0,0.0,0.0,-4.441610,-6.944828,-5.812156,-8.315374,-7.439613,-9.942831,85.487108,14.512892,96.001235,2.300448,0.000000,0.0,0.308785,0.000000,0.000000,48.0,435490.0,88.410067,4.740407,0.115502,1.307722,0.010104,2.769983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000227,0.000223,21.7,NaN,1.0,-0.220062,-1.846636,5.911994,35.655794,0.519686,0.097179,NaN,0.700000,0.300000,0.200000,0.0000,0.0,0.0,0.0,0.200000,0.000000,0.0,0.0,0.1,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.100000,0.0,0.0,0.400000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.200000,10.0,7.0,1.600000,5.0,0.320000,0.172414,1.470808,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,299.0,0.0,0.00000,0.00000,0.047619,0.047619,0.0,0.0,0.0,0.904762,0.047619,0.0,1.0,0.000002,0.0,0.0,0,0
4,10005.0,SRCTQ,853887206,None,D,USA,323111,OH,11,Management Occupations,11-3121,Human Resources Managers,Standard Register,92,Public Administration,923,-999,-999,-999,Arizona,Maricopa,4,13,4013,38060,"Phoenix-Mesa-Scottsdale, AZ",2010,1,0.0,2.0,0.0,0.0,1.0,NaN,NaN,3.3,2.0,1.5,0.2,1.4,3.1,5.7,4.3,2.0,1.3,1.9,3.4,6.7,980.0,7.5,0.585,67700.0,108600.0,0.000465,0.048816,NaN,1014.0,0.029511,0.001516,0.000059,-0.008672,-0.260187,15.637158,0.161711,0.150436,-1.719606,-197.247930,10.568001,0.007554,11.459020,1.764027,10.305456,-0.736331,-0.476211,1.272905,10.114192,9.492968,9.771675,15.040650,0.483729,12.459256,10.032712,-1.100469,-0.501410,0.004411,NaN,NaN,0.064033,0.296579,0.009060,2787165.0,3116147.0,328982.0,10.6,14.550195,14.447057,12.227384,9.8,14.375187,14.476564,12.137387,9.6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,-3.648719,-5.971530,-5.592751,-7.915562,-7.158480,-9.481291,44.593895,55.406105,89.821521,4.940507,0.000000,0.0,1.784790,0.000000,1.784790,46.0,4211213.0,80.513690,5.093711,2.119318,3.236811,0.226847,6.137733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000475,0.000466,28.3,NaN,1.0,-0.220062,-1.846636,5.911994,35.655794,0.519686,0.097179,NaN,0.285714,0.714286,0.428571,0.0000,0.0,0.0,0.0,0.071429,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.071429,0.0,0.285714,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.571429,14.0,5.0,1.285714,4.0,0.321429,0.137931,1.054721,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,531.0,0.0,0.03125,0.03125,0.000000,0.000000,0.0,0.0,0.0,0.937500,0.062500,0.0,1.0,0.000002,0.0,1.0,0,0

In [20]:
count = df[(df['gvkey'] == '-999') & (df['cusip']!= '-999')].shape[0]
print(f"Number of rows where 'col1' is -999 and 'col2' is NaN: {count}")

Number of rows where 'col1' is -999 and 'col2' is NaN: 0

In [29]:
groupby_cols = ['gvkey', 'tic', 'cusip', 'comCounty', 'comDom', 'comCountry', 'comNAICS', 'comHeadquarters', 
        'OccFam', 'OccFamName', 'SOC', 'SOCName', 'CanonEmployer', 'Sector', 'SectorName', 
        'NAICS3', 'NAICS4', 'NAICS5', 'NAICS6', 'State', 'County', 
        'FIPSState', 'FIPSCounty', 'FIPS', 'BestFitMSA', 'BestFitMSAName', 'Year', 'qtr']

In [30]:
numeric_cols = [col for col in df.columns if col not in groupby_cols]
df[numeric_cols] = df[numeric_cols].replace(-999, np.nan)

In [31]:
df['bartik'] = df['BShareimq']*df['shiftNAICS']
df['MeanWage'] = np.log(df['MeanWage'])
df = df.dropna(subset=['tight', 'bartik'])

In [7]:
df.dtypes

gvkey                                      object
tic                                        object
cusip                                      object
comCounty                                  object
comDom                                     object
comCountry                                 object
comNAICS                                    int64
comHeadquarters                            object
OccFam                                      int64
OccFamName                                 object
SOC                                        object
SOCName                                    object
CanonEmployer                              object
Sector                                      int64
SectorName                                 object
NAICS3                                      int64
NAICS4                                      int64
NAICS5                                      int64
NAICS6                                      int64
State                                      object
County                                     object
FIPSState                                   int64
FIPSCounty                                  int64
FIPS                                        int64
BestFitMSA                                  int64
BestFitMSAName                             object
Year                                        int64
Month                                       int64
qtr                                         int64
BGTJobId                                  float64
Degree                                    float64
Exp                                       float64
boncom                                    float64
parttime                                  float64
NoWage                                    float64
MeanWage                                  float64
VarRange                                  float64
hires_nt                                  float64
jobOpenings_nt                            float64
layoffs_nt                                float64
otherSeparations_nt                       float64
quits_nt                                  float64
totalSeparations_nt                       float64
unemployedPerOpening_nt                   float64
hires_st                                  float64
jobOpenings_st                            float64
layoffs_st                                float64
quits_st                                  float64
totalSeparations_st                       float64
unemployedPerOpening_st                   float64
tot_emp                                   float64
emp_prse                                  float64
jobs_1000                                 float64
natEmp                                    float64
a_mean_nt                                 float64
SOCShare                                  float64
0507SOCShare                              float64
shiftSOC                                  float64
wkWageNAICS                               float64
shiftNAICS                                float64
07LNAICSShare                             float64
BShareimq                                 float64
BShareHK                                  float64
DivIntRent                                float64
UIC                                       float64
earnWork                                  float64
emplGovContr                              float64
emplPensionContr                          float64
farmPropInc                               float64
incManBen                                 float64
netEarnbyRes                              float64
nonfarmPropInc                            float64
pInc                                      float64
pTransReceipt                             float64
percapDivRent                             float64
percapEarn                                float64
percapInc                                 float64
percapIncMan                              float64
percapRet                                 float64
percapTrans                               float64
percapUIC                                 float64
pop                                       float64
propInc                                   float64
retirement                                float64
supplWages                                float64
wages                                     float64
lgdp_change                               float64
igdpq_ch                                  float64
crisis_ch                                 float64
lpctunion                                 float64
pctunion_ind                              float64
pctunion_occ                              float64
employment_st                             float64
laborForce_st                             float64
unemployment_st                           float64
unemploymentRate_st                       float64
laborForce_msa                            float64
employment_msa                            float64
unemployment_msa                          float64
unemploymentRate_msa                      float64
employment_ct                             float64
laborForce_ct                             float64
unemployment_ct                           float64
unemploymentRate_ct                       float64
MSAopenings_employer                      float64
FIPSopenings_employer                     float64
MSAOccopenings_employer                   float64
FIPSOccopenings_employer                  float64
MSASectoropenings_employer                float64
FIPSSectoropenings_employer               float64
TopQuartileMSAopenings                    float64
TopQuartileFIPSopenings                   float64
TopQuartileMSAOccopenings                 float64
TopQuartileFIPSOccopenings                float64
TopQuartileMSASectoropenings              float64
TopQuartileFIPSSectoropenings             float64
tight                                     float64
vacan                                     float64
tightocc                                  float64
vacanocc                                  float64
tightsector                               float64
vacansector                               float64
Male                                      float64
Female                                    float64
white                                     float64
black                                     float64
americanIndian                            float64
alaskaNative                              float64
asian                                     float64
hawaiianPacificIslander                   float64
someOtherRace                             float64
ageMean                                   float64
pop_msa                                   float64
white_msa                                 float64
black_msa                                 float64
americanIndianAlaskaNative_msa            float64
asian_msa                                 float64
nativeHawaiianPacificIslander_msa         float64
someOtherRace_msa                         float64
kcosts                                    float64
kprod                                     float64
kshare                                    float64
ktolb                                     float64
hworked                                   float64
lcomp                                     float64
lprod                                     float64
lshare                                    float64
opw                                       float64
routput                                   float64
tfp                                       float64
ulc                                       float64
intmig                                    float64
dommig                                    float64
college_st                                float64
nonprofit                                 float64
quarter                                   float64
roa                                       float64
roe                                       float64
logSize                                   float64
gProfit                                   float64
tobinq                                    float64
lev                                       float64
comAge                                    float64
IsSpecialized                             float64
IsBaseline                                float64
IsSoftware                                float64
Administration                            float64
agricultureHorticulture                   float64
Analysis                                  float64
architectureConstruction                  float64
Business                                  float64
customerClient                            float64
Design                                    float64
economicsPolicy                           float64
educationTraining                         float64
energyUtilities                           float64
Engineering                               float64
Environment                               float64
Finance                                   float64
healthCare                                float64
humanResources                            float64
industryKnowledge                         float64
informationTechnology                     float64
Legal                                     float64
maintenanceRepair                         float64
manufacturingProduction                   float64
marketingPublic                           float64
mediaWriting                              float64
personalCare                              float64
publicSafety                              float64
Religion                                  float64
Sales                                     float64
scienceResearch                           float64
supplyChain                               float64
notMapped                                 float64
SkillsCount                               float64
SkillClusterCount                         float64
SkillClusterbyFam                         float64
SkillFamilyCount                          float64
ClusterToFamilyRatio                      float64
SkillFamilyCoverage                       float64
SkillFamilyEntropy                        float64
pecuniary_benefits_count                  float64
job_design_characteristics_count          float64
career_development_opportunities_count    float64
organizational_culture_count              float64
meaningful_work_count                     float64
environmental_initiatives_count           float64
social_initiatives_count                  float64
job_tasks_requirements_count              float64
main_count                                float64
length                                    float64
sr_count                                  float64
pecuniary_benefits_prop                   float64
job_design_characteristics_prop           float64
career_development_opportunities_prop     float64
organizational_culture_prop               float64
meaningful_work_prop                      float64
environmental_initiatives_prop            float64
social_initiatives_prop                   float64
job_tasks_requirements_prop               float64
main_prop                                 float64
sr_prop                                   float64
Openingstotal_employer                    float64
dtype: object

In [17]:
df.tight.describe()

count    563357.000000
mean        -19.938021
std         124.154600
min        -999.000000
25%          -5.516107
50%          -4.062753
75%          -2.805379
max           0.977351
Name: tight, dtype: float64

## Merge Text Measures - Main

In [126]:
df_txt= pd.read_parquet('/Users/mgor/Dropbox/Second YPP/Data/Data Aux/US_XML_AddFeed_20210701_20210707.parquet')

In [127]:
df_txt.head()

         JobID                 CanonEmployer     JobDate  \
0  39032229262  Lindley Park Filling Station  2021-06-30
1  39032229346              Northrop Grumman  2021-06-30
2  39032229414                Uniform Outlet  2021-06-30
3  39032229428                Hallmark Cards  2021-06-30
4  39032229249             Prime Hospitality  2021-06-30

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        JobText  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Bar Manager/Head Bartender\n\nLindley Park Filling Station\n\nGreensboro, NC 27403\n\nJob details\n\nJob Type\n\nFull-time\n\nNumber of hires for this role\n\n1\n\nQualifications\n\n*\n*\n\nBartending: 3 years (Preferred)\n\n*\n\nNight Shift (Preferred)\n\nFull Job Description\n\nWe are hiring a dedicated bar manager for a small but busy restaurant. We are primarily a restaurant, so menu knowledge and food service will be required. But in this role, the bar will be "your baby"! You will be responsible for all ordering, making/changing lists, staff training, and building a clientele. The ideal candidate will have a vast knowledge of beer, wine, and basic cocktails, experience with ordering/pars/inventory, a great deal of patience, and an extremely positive attitude. Customers should want to sit at the bar because YOU are there! Established relationships with vendors is a major plus. Nights and weekends are definitely required, but we close at 10- no late nights!\n\nJob Type: Full-time\n\nPay: $7.00 - $12.00 per hour\n\nBenefits:\n\n* Employee discount\n* Flexible schedule\n\nSchedule:\n\n* Day shift\n* Night shift\n* Weekend availability\n\nSupplemental Pay:\n\n* Tips\n\nCOVID-19 considerations:\nExtra sanitization in place, all non-vaccinated staff required to wear masks at all times.\n\nExperience:\n\n* Bartending: 3 years (Preferred)\n\nShift Availability:\n\n* Night Shift (Preferred)\n\nWork Location:\n\n* One location\n\nWork Remotely:\n\n* No
1                                                                                                                                                                                                                                                                                                                       Manager, Human Resources Business Partner 1\n\nNorthrop Grumman\n\nChandler, AZ\n\nRemote\n\n* Job\n* Company\n\n* Category: Human Resources\n* Location: Chandler, Arizona\n* US Citizenship Required for this Position: Yes\n* Clearance Type: None\n* Telecommute: Yes May Consider Occasional/Part Time Teleworking for this position\n* Shift: 1st Shift\n* Travel Required: Yes, 10 % of the Time\n* Positions Available: 1\n\nEmbark on a career putting innovative, reliable, and agile products and ideas into orbit, and beyond. Northrop Grumman has opportunities waiting for you that play a vital role in human space exploration, national defense, and scientific discovery, supporting multiple programs across the universe. With us, youll discover a culture of curiosity and collaboration that will have you Defining Possible from the day you start. Our space systems connect and protect millions of people on earth every day, now and for the future. Explore your future and launch your career today. Are you interested in expanding your career through experience and exposure, all while supporting a mission that seeks to ensure the security of our nation and its allies? If so, then Northrop Grumman is the place for you. Northrop Grumman is currently seeking a HR Manager to provide leadership within our Launch Vehicles Business Unit and employee teams in our Chandler, Arizona location. As a HR Manager you will partner with the HR Director to drive strategic human capital plans that support sector and enterprise goals, providing HR guidance and counsel to leaders and managers regarding succession planning and talent development, reward and recognition, compensation, organization effectiveness, performance management, staffing and employee relations. Specific duties and responsibilities include the following:\n* Establish a solid understanding of the business, build and expand relationships with program leadership teams, and create close partnerships across HR centers of excellence (COE's)\n* Identify trends, risks, and opportunities within the organization and develop solutions in partnership with programs\n* Provide business insight through data analytics, research and benchmarking to inform and recommend solutions to enable business growth\n* Play a key change leadership role in the company's transformation by reinforcing a culture of growth and innovation\n* Leadership Development-focused on comprehensive succession planning and strategic leadership movement. Partner with business leaders to build leadership depth to support the development and succession planning process\n* Lead a team of HR Business Partners\n* Serve as the HR Business Partner to a small internal customers base (apx 100 employees and leaders)\n\nBasic Qualifications:\n* Must have a Bachelor's degree in HR or related field and a minimum of 6 years of HR experience, or a master's degree in HR related field with a minimum of 4 years of HR experience\n* Demonstrated ability to communicate within various levels of the organization and excellent negotiation skills\n* Demonstrated success in building or enhancing a collaborative work environment\n* Demonstrated leadership and relationship building skills\n* Demonstrated ability to plan, organize, implement and close multiple projects simultaneously on various topics within the HR work streams\n* Have the capacity to understand people issues impacting the business\n* Demonstrated integrity in business interactions and honor personal commitments\n* Possess the proven ability to communicate clearly both in writing and verbally\n* Have proven ability to influence others\n* Have excellent attention detail\n* Initiative to identify and anticipate needs and make recommendations for implementation\n\nNorthrop Grumman is committed to hiring and retaining a diverse workforce. We are proud to be an Equal Opportunity/Affirmative Action Employer, making decisions without regard to race, color, religion, creed, sex, sexual orientation, gender identity, marital status, national origin, age, veteran status, disability, or any other protected class. For our complete EEO/AA and Pay Transparency statement, please visit www.northropgrumman.com/EEO. U.S. Citizenship is required for most positions.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           SALES ASSOCIATE\n\nThe Uniform Outlet is a specialty retailer that specializes in brand name scrubs and medical uniforms for men and women. From the start, our philosophy has been simple: Great Selection, Great Prices, and No Gimmicks. The Uniform Outlet strives to meet or exceed our customers expectations through providing excellent customer service and tremendous value on quality products.\n\nWe are currently seeking qualified candidates for the position of PART-TIME SALES ASSOCIATE at our Johnson Creek, WI Location. As a Sales Associate you will provide a complete shopping experience for our customers, which involves product knowledge, personal assistance, as well as maintaining the highest level of store presentation standards.\n\nThe Position Responsibilities:\n\n* Provide friendly and helpful customer service.\n* Ringing purchases at the register.\n* Folding, hanging, and stocking merchandise.\n* Light cleaning (vacuuming & dusting).\n* Opening and closing store.\n\nRequirements:\n\n* Must be 18 or older.\n* Previous retail or related customer service experience preferred, but not required.\n* Accuracy with money handling and cash register use.\n* Excellent problem solving, interpersonal, written, and verbal communication skills.\n* Self-motivated and ability to work alone or as part of a team.\n* Flexible Hours; must have some evening, weekend, and holiday availability.\n* Occasional heavy lifting and ability to stand during the majority of shift.\n* Reliable transportation.\n\nCompensation  We offer a competitive wage, flexible scheduling, opportunities for advancement, and a generous employee discount.\n\nWe value and support diversity and equal opportunities for employment.\n\nQualified candidates can apply online at www.theuniformoutlet.com/careers or in person at our store location (575 West Linmar Lane, Suite A  140, Johnson Creek, WI).\n\nJob Type: Part-time\n\nPay: $10.00 per hour\n\nBenefits:\n\n* Employee discount\n* Flexible schedule\n\nSchedule:\n\n* Monday to Friday\n* Weekends\n\nEducation:\n\n* High school or equivalent (Preferred)\n\nExperience:\n\n* Customer Service: 1 year (Preferred)\n\nWork Location:\n\n* Multiple locations\n\nWork Remotely:\n\n* No\n\nShow more

In [64]:
df = df.dropna(subset = ['JobText'])
df= df[(df['CanonEmployer'].notna()) & (df['CanonEmployer'] != None) & (df['CanonEmployer'] != "None")]
df = df.drop(columns=['IsDuplicate','IsDuplicateOf', 'JobReferenceID'])

# Date
df['year'] = df.JobDate.apply(lambda x: x[0:4])
df['month'] = df.JobDate.apply(lambda x: x[5:7])

In [91]:

df_txt=df_txt.rename(columns={'JobID':'BGTJobId'}, errors='ignore')
df_txt.drop(columns=['CanonEmployer', 'JobText', 'CleanText','year'], inplace=True, errors='ignore')

In [55]:
df_txt['month']=df_txt['JobDate'].str[5:7].astype(int)

In [123]:
df_txt=pd.read_parquet('/Users/mgor/Dropbox/Second YPP/Data/Data Aux/Text_2010-12.parquet')

In [56]:
df_merge=pd.merge(df, df_txt, on=['BGTJobId'], how='left',indicator=True)

In [67]:
df.month.value_counts()

11    33242
12    27376
Name: month, dtype: int64

## Merge Skills-Main

In [82]:
df= pd.read_parquet('/Users/mgor/Dropbox/Second YPP/Data/Data Aux/Main_2014-12.parquet')

In [97]:
df_skill= pd.read_parquet('/Users/mgor/Dropbox/Second YPP/Data/Data Aux/Skills_2018-01.parquet')

In [93]:
df_txt['BGTJobId']=pd.to_numeric(df_txt['BGTJobId'], errors='coerce').astype(int)

In [96]:
df_skill.dtypes

BGTJobId                      int64
IsSpecialized               float64
IsBaseline                  float64
IsSoftware                  float64
Administration              float64
agricultureHorticulture     float64
Analysis                    float64
architectureConstruction    float64
Business                    float64
customerClient              float64
Design                      float64
economicsPolicy             float64
educationTraining           float64
energyUtilities             float64
Engineering                 float64
Environment                 float64
Finance                     float64
healthCare                  float64
humanResources              float64
industryKnowledge           float64
informationTechnology       float64
Legal                       float64
maintenanceRepair           float64
manufacturingProduction     float64
marketingPublic             float64
mediaWriting                float64
personalCare                float64
publicSafety                float64
Religion                    float64
Sales                       float64
scienceResearch             float64
supplyChain                 float64
notMapped                   float64
SkillsCount                 float64
SkillClusterCount           float64
SkillClusterbyFam           float64
SkillFamilyCount            float64
ClusterToFamilyRatio        float64
SkillFamilyCoverage         float64
SkillFamilyEntropy          float64
dtype: object

In [63]:
df=df.drop(columns=['CanonTitle','BGTOccGroupName2','BGTCareerAreaName2','MSAName'], errors='ignore')

In [64]:
df = df.drop(columns=[col for col in df.columns if col.endswith('_y')], errors='ignore')
df = df.rename(columns={col: col[:-2] for col in df.columns if col.endswith('_x')})

In [89]:
df=df.drop_duplicates(subset='BGTJobId')

In [90]:
df_aux=pd.merge(df, df_skill, on=['BGTJobId'], how='inner', indicator=True)

## Skills

In [76]:
df= pd.read_table('/Users/mgor/Dropbox/Second YPP/Data/Data Aux/Skills_2010-01.zip', encoding='latin')

In [77]:
# Initialize the encoder
encoder = OneHotEncoder(sparse=True, dtype=int)
# Fit and transform the categorical column
encoded = encoder.fit_transform(df[['SkillClusterFamily']])

# Create a DataFrame from the encoded sparse matrix
encoded_df = pd.DataFrame.sparse.from_spmatrix(
    encoded, columns=encoder.get_feature_names_out(['SkillClusterFamily'])
)

# Rename the columns to remove the prefix
encoded_df.columns = [col.replace('SkillClusterFamily_', '') for col in encoded_df.columns]

# Concatenate the encoded DataFrame with the original DataFrame
df = pd.concat([df.reset_index(drop=True), encoded_df.reset_index(drop=True)], axis=1)

In [78]:
def rename_column(col_name):
        # Special case for 'na'
        if col_name.lower() == 'na':
            return 'notMapped'
        
        # Process columns with spaces only
        if ' ' in col_name:
            # Remove commas and "and"
            cleaned_name = re.sub(r',', '', col_name)
            cleaned_name = re.sub(r'\band\b', '', cleaned_name, flags=re.IGNORECASE)
            
            # Split into words
            words = cleaned_name.split()
            
            # Take the first two words only and apply camelCase
            if len(words) > 1:
                return words[0].lower() + words[1].capitalize()
            else:
                return words[0].lower()
        
        # Return original name for other cases
        return col_name

# Apply renaming logic
df = df.rename(columns={col: rename_column(col) for col in df.columns})

In [79]:
df.head()

,BGTJobId,JobDate,Skill,SkillCluster,SkillClusterFamily,IsSpecialized,IsBaseline,IsSoftware,Salary,Administration,agricultureHorticulture,Analysis,architectureConstruction,Business,customerClient,Design,economicsPolicy,educationTraining,energyUtilities,Engineering,Environment,Finance,healthCare,humanResources,industryKnowledge,informationTechnology,Legal,maintenanceRepair,manufacturingProduction,marketingPublic,mediaWriting,personalCare,publicSafety,Religion,Sales,scienceResearch,supplyChain,notMapped
0,289187887,2010-01-11,Customer Service,Basic Customer Service,Customer and Client Support,1,0,0,-999,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,289187887,2010-01-11,Sales Management,Sales Management,Sales,1,0,0,-999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,289187887,2010-01-11,Online Sales,Online Sales,Sales,1,0,0,-999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,289187887,2010-01-11,Cash Handling,Cash Register Operation,Customer and Client Support,1,0,0,-999,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,289187887,2010-01-11,Sales,General Sales,Sales,1,0,0,-999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [80]:
df['SkillsCount'] = df.groupby('BGTJobId')['Skill'].transform('nunique')
df['SkillClusterCount'] = df.groupby('BGTJobId')['SkillCluster'].transform('nunique')
df['SkillClusterbyFam'] = df.groupby(['BGTJobId', 'SkillClusterFamily'])['SkillCluster'].transform('nunique')
df['SkillFamilyCount'] = df.groupby('BGTJobId')['SkillClusterFamily'].transform('nunique')
df['ClusterToFamilyRatio'] = df['SkillClusterbyFam'] / df['SkillFamilyCount']

total_families = df['SkillClusterFamily'].nunique()
df['SkillFamilyCoverage'] = (
    df['SkillFamilyCount'] / total_families
)

In [8]:
def calculate_entropy(series):
    counts = series.value_counts(normalize=True)
    return entropy(counts)

df['SkillFamilyEntropy'] = df.groupby('BGTJobId')['SkillClusterFamily'].transform(calculate_entropy)

In [81]:
df.drop(columns=['JobDate', 'Skill', 'SkillCluster', 'SkillClusterFamily', 'Salary'], inplace=True)

In [82]:
# Convert only sparse columns to dense
sparse_cols = [col for col in df.columns if pd.api.types.is_sparse(df[col])]
df[sparse_cols] = df[sparse_cols].sparse.to_dense()

In [83]:
df.head()

,BGTJobId,IsSpecialized,IsBaseline,IsSoftware,Administration,agricultureHorticulture,Analysis,architectureConstruction,Business,customerClient,Design,economicsPolicy,educationTraining,energyUtilities,Engineering,Environment,Finance,healthCare,humanResources,industryKnowledge,informationTechnology,Legal,maintenanceRepair,manufacturingProduction,marketingPublic,mediaWriting,personalCare,publicSafety,Religion,Sales,scienceResearch,supplyChain,notMapped,SkillsCount,SkillClusterCount,SkillClusterbyFam,SkillFamilyCount,ClusterToFamilyRatio,SkillFamilyCoverage
0,289187887,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,7,2,3,0.666667,0.103448
1,289187887,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,8,7,4,3,1.333333,0.103448
2,289187887,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,8,7,4,3,1.333333,0.103448
3,289187887,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,7,2,3,0.666667,0.103448
4,289187887,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,8,7,4,3,1.333333,0.103448

In [84]:
df = df.groupby('BGTJobId').mean().reset_index()

In [13]:
df.to_parquet('/Users/mgor/Library/CloudStorage/Dropbox/Second YPP/Data/Other data/test.parquet', compression='snappy', index=False)

In [85]:
len(df)

260088