In [1]:
import pandas as pd
import re
import nltk
import numpy as np

import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import statsmodels.api as sm
from pathlib import Path

In [3]:
df_tt= pd.read_table('/Users/mgor/Documents/Strategy/2YP/Data/data_merged/Merged_main/panel_clean.csv.zip', delimiter=',', header=0)

In [4]:
df_tt.replace([np.inf, -np.inf], np.nan, inplace=True)

In [4]:
df_tt.to_stata('main.dta')

/opt/anaconda3/lib/python3.7/site-packages/pandas/io/stata.py:2397: InvalidColumnName:
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    ifelse(atq > 0, atq, NA)   ->   ifelse_atq___0__atq__NA_
    ST FIPS Code   ->   ST_FIPS_Code
    Unemployment Rate   ->   Unemployment_Rate

If this is not what you expect, please make sure you have Stata-compliant
column names in your DataFrame (strings only, max 32 characters, only
alphanumerics and underscores, no Stata reserved words)

  warnings.warn(ws, InvalidColumnName)

In [13]:
df_tt

,year,quarter,employer,gvkey,MSA,BestFitMSA,full_wilzha,career_mean,work_mean,sdgs,...,roe,meq,tonbiq,mlev,rd_at,cash_at,gprofit,tang,capxq,capx_at
0,2010,1.0,1-800-FLOWERS.COM,122519,10580.0,10580,0.000000,0.000000,0.0,0.001852,...,-0.057157,238.796476,1.305402,0.346814,NaN,0.009912,0.126257,0.175968,2.489303,0.007601
1,2010,1.0,1-800-FLOWERS.COM,122519,16980.0,16980,0.000000,0.000000,0.0,0.007380,...,-0.057157,238.796476,1.305402,0.346814,NaN,0.009912,0.126257,0.175968,2.489303,0.007601
2,2010,1.0,1-800-FLOWERS.COM,122519,17460.0,17460,0.000000,0.000000,0.0,0.000000,...,-0.057157,238.796476,1.305402,0.346814,NaN,0.009912,0.126257,0.175968,2.489303,0.007601
3,2010,1.0,1-800-FLOWERS.COM,122519,35620.0,35620,0.000000,0.000137,0.0,0.000410,...,-0.057157,238.796476,1.305402,0.346814,NaN,0.009912,0.126257,0.175968,2.489303,0.007601
4,2010,1.0,21ST CENTURY ONCOLOGY HLDGS,265008,11460.0,11460,0.000000,0.000000,0.0,0.001748,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4967493,2021,4.0,ZYNGA INC,187576,16980.0,16980,0.002137,0.000000,0.0,0.020211,...,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876
4967494,2021,4.0,ZYNGA INC,187576,21660.0,21660,0.000000,0.000000,0.0,0.022951,...,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876
4967495,2021,4.0,ZYNGA INC,187576,31080.0,31080,0.002110,0.000000,0.0,0.023207,...,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876
4967496,2021,4.0,ZYNGA INC,187576,41740.0,41740,0.000000,0.000000,0.0,0.022876,...,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876
4967497,2021,4.0,ZYNGA INC,187576,41860.0,41860,0.001544,0.001907,0.0,0.025633,...,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876

In [ ]:
df_tt.columns.to_list()

In [ ]:
df_panel=df_tt[(df_tt._merge == 'both') ]

In [38]:
df_aux=df_tt2[(df_tt2.year >2016) & (df_tt2.year <2020) ]

In [39]:
df_aux

,year,quarter,employer,gvkey,MSA,BestFitMSA,full_wilzha,career_mean,work_mean,sdgs,csr,prosocial,employee,environ,hum_rig,soc_com,exp,min_wage,max_wage,min_hour_wage,max_hour_wage,occ_arch_mean,occ_art_mean,occ_clean_mean,occ_bus_mean,occ_soc_com_mean,occ_math_mean,occ_constr_mean,occ_educ_mean,occ_farm_mean,occ_food_mean,occ_health_prac_mean,occ_health_sup_mean,occ_inst_mean,occ_legal_mean,occ_sci_mean,occ_manage_mean,occ_mil_mean,occ_not_defined_mean,occ_off_adm_mean,occ_care_mean,occ_prod_mean,occ_protec_mean,occ_sales_mean,occ_trans_mean,spe_skill_mean,base_skill_mean,softw_skill_mean,high_sec_educ_mean,assoc_educ_mean,bach_educ_mean,mast_educ_mean,phd_educ_mean,occ_arch_sum,occ_art_sum,occ_clean_sum,occ_bus_sum,occ_soc_com_sum,occ_math_sum,occ_constr_sum,occ_educ_sum,occ_farm_sum,occ_food_sum,occ_health_prac_sum,occ_health_sup_sum,occ_inst_sum,occ_legal_sum,occ_sci_sum,occ_manage_sum,occ_mil_sum,occ_not_defined_sum,occ_off_adm_sum,occ_care_sum,occ_prod_sum,occ_protec_sum,occ_sales_sum,occ_trans_sum,high_sec_educ_sum,assoc_educ_sum,bach_educ_sum,mast_educ_sum,phd_educ_sum,tot_post_sum,datadate,indfmt,consol,popsrc,datafmt,tic,cusip,conm,curcdq,datacqtr,datafqtr,atq,ceqq,cheq,cogsq,cshoq,dlcq,dlttq,ibq,invfgq,niq,oibdpq,ppentq,revtq,saleq,xrdq,xsgaq,capxy,cogsy,oibdpy,revty,saley,xrdy,xsgay,costat,fic,prccq,sic,date,cpi,"ifelse(atq > 0, atq, NA)",logSize,roe,meq,tonbiq,mlev,rd_at,cash_at,gprofit,tang,capxq,capx_at
2444456,2017,1.0,1-800-FLOWERS.COM,122519,31080.0,31080,0.000000,0.000000,0.0,0.000000,0.016667,0.016667,0.000000,0.016667,0.000000,0.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,1.00000,1.000000,0.000000,0.000000,1.000000,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1,20160930.0,INDL,C,D,STD,FLWS,68243Q106,1-800-FLOWERS.COM,USD,2016Q3,2017Q1,585.802811,219.407168,6.566021,89.231670,65.282,142.279991,86.923233,-15.329788,104.676277,-15.329788,-14.689224,163.480804,161.189743,161.189743,NaN,84.079091,4.571428,94.442,-14.689224,165.829,165.829,NaN,86.499,A,USA,8.913459,5961.0,2017-01-01,102.878134,602.663,6.372983,-0.069869,581.888412,1.618777,0.282586,NaN,0.011209,0.122837,0.279071,4.571428,0.007804
2444457,2017,1.0,1-800-FLOWERS.COM,122519,40060.0,40060,0.000000,0.000000,0.0,0.000000,0.013889,0.013889,0.000000,0.013889,0.013889,0.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,1.000000,0.00000,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,20160930.0,INDL,C,D,STD,FLWS,68243Q106,1-800-FLOWERS.COM,USD,2016Q3,2017Q1,585.802811,219.407168,6.566021,89.231670,65.282,142.279991,86.923233,-15.329788,104.676277,-15.329788,-14.689224,163.480804,161.189743,161.189743,NaN,84.079091,4.571428,94.442,-14.689224,165.829,165.829,NaN,86.499,A,USA,8.913459,5961.0,2017-01-01,102.878134,602.663,6.372983,-0.069869,581.888412,1.618777,0.282586,NaN,0.011209,0.122837,0.279071,4.571428,0.007804
2444458,2017,1.0,1-800-FLOWERS.COM,122519,47900.0,47900,0.000000,0.000000,0.0,0.000000,0.017857,0.017857,0.000000,0.017857,0.017857,0.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,1.000000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,20160930.0,INDL,C,D,STD,FLWS,68243Q106,1-800-FLOWERS.COM,USD,2016Q3,2017Q1,585.802811,219.407168,6.566021,89.231670,65.282,142.279991,86.923233,-15.329788,104.676277,-15.329788,-14.689224,163.480804,161.189743,161.189743,NaN,84.079091,4.571428,94.442,-14.689224,165.829,165.829,NaN,86.499,A,USA,8.913459,5961.0,2017-01-01,102.878134,602.663,6.372983,-0.069869,581.888412,1.618777,0.282586,NaN,0.011209,0.122837,0.279071,4.571428,0.007804
2444459,2017,1.0,10X GENOMICS INC,35640,16980.0,16980,0.000000,0.000000,0.0,0.009740,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.000000,0.0,0.000000,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.791667,0.208333,0.041667,0.000000,0.0,1.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1,20170331.0,INDL,C,D,STD,TXG,88025U109,10X GENOMICS INC,USD,2017Q1,2017Q1,NaN,NaN,NaN,1.886826,NaN,NaN,NaN,-6.109170,NaN,-6.109170,NaN,NaN,11.683727,11.683727,7.016068,15.686521,NaN,1.997,NaN,12.020,12.020,7.016068,16.138,A,USA,NaN,2835.0,2017-01-01,102.878134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2444460,2017,1.0,10X GENOMICS INC,35640,41860.0,41860,0.000000,0.000061,0.0,0.001234,0.014684,0.014326,0.002838,0.006760,0.004495,0.007641,-37.500000,-999.000000,-999.000000,-999.000000,-999.000000,0.083333,0.062500,0.0,0.104167,0.0,0.395833,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.020833,0.062500,0.0,0.020833,0.187500,0.0,0.0,0.0,0.062500,0.00000,0.755977,0.244023,0.216552,0.226316,0.0,0.642105,0.00000,0.131579,4.0,3.0,0.0,2.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,3.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0,16.0,0.0,5.0,30,20170331.0,INDL,C,D,STD,TXG,88025U109,10X GENOMICS INC,USD,2017Q1,2017Q1,NaN,NaN,NaN,1.886826,NaN,NaN,NaN,-6.109170,NaN,-6.109170,NaN,NaN,11.683727,11.683727,7.016068,15.686521,NaN,1.997,NaN,12.020,12.020,7.016068,16.138,A,USA,NaN,2835.0,2017-01-01,102.878134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3916402,2019,4.0,ZYNGA INC,187576,12420.0,12420,0.001977,0.000069,0.0,0.021708,0.037537,0.040958,0.027963,0.007418,0.031746,0.026270,-497.335317,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.051587,0.0,0.023810,0.0,0.625000,0.0,0.027778,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.164683,0.0,0.083333,0.000000,0.0,0.0,0.0,0.000000,0.02381,0.737950,0.262050,0.270665,0.000000,0.0,0.682540,0.31746,0.000000,0.0,2.0,0.0,1.0,0.0,20.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,15.0,4.0,0.0,34,20191231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2019Q4,2019Q4,3365.698651,1816.280571,1279.396408,103.208523,950.042,14.483868,644.300899,-3.218024,0.000000,-3.218024,50.899033,149.682269,371.877661,371.877661,96.014816,208.726581,21.732698,444.644,5.271124,1321.659,1321.659,465.132332,871.282,I,USA,5.626946,7372.0,2019-10-01,108.762381,3660.614,8.121391,-0.001772,5345.834626,2.048684,0.109713,0.028527,0.380128,0.079826,0.044473,4.342972,0.001290
3916403,2019,4.0,ZYNGA INC,187576,16980.0,16980,0.000000,0.000000,0.0,0.017874,0.033441,0.036271,0.029146,0.006396,0.029100,0.024117,-497.250000,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.250000,0.0,0.000000,0.0,0.250000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.250000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.250000,0.00000,0.667201,0.332799,0.259615,0.000000,0.0,1.000000,0.00000,0.000000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,4,20191231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2019Q4,2019Q4,3365.698651,1816.280571,1279.396408,103.208523,950.042,14.483868,644.300899,-3.218024,0.000000,-3.218024,50.899033,149.682269,371.877661,371.877661,96.014816,208.726581,21.732698,444.644,5.271124,1321.659,1321.659,465.132332,871.282,I,USA,5.626946,7372.0,2019-10-01,108.762381,3660.614,8.121391,-0.001772,5345.834626,2.048684,0.109713,0.028527,0.380128,0.079826,0.044473,4.342972,0.001290
3916404,2019,4.0,ZYNGA INC,187576,21660.0,21660,0.000000,0.000000,0.0,0.028818,0.043228,0.046110,0.037464,0.008646,0.037464,0.028818,4.000000,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.000000,0.0,0.000000,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.846154,0.153846,0.538462,0.000000,0.0,1.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1,20191231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2019Q4,2019Q4,3365.698651,1816.280571,1279.396408,103.208523,950.042,14.483868,644.300899,-3.218024,0.000000,-3.218024,50.899033,149.682269,371.877661,371.877661,96.014816,208.726581,21.732698,444.644,5.271124,1321.659,1321.659,465.132332,871.282,I,USA,5.626946,7372.0,2019-10-01,108.762381,3660.614,8.121391,-0.001772,5345.834626,2.048684,0.109713,0.028527,0.380128,0.079826,0.044473,4.342972,0.001290
3916405,2019,4.0,ZYNGA INC,187576,41740.0,41740,0.000000,0.000507,0.0,0.021838,0.031294,0.033383,0.022834,0.001815,0.023898,0.019237,-329.500000,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.166667,0.0,0.000000,0.0,0.833333,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.813938,0.186062,0.467349,0.000000,0.0,1.000000,0.00000,0.000000,0.0,1.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5,20191231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2019Q4,2019Q4,3365.698651,1816.280571,1279.396408,103.208523,950.042,14.483868,644.300899,-3.218024,0.000000,-3.218024,50.899033,149.682269,371.877661,371.877661,96.014816,208.726581,21.732698,444.644,5.271124,1321.659,1321.659,465.132332,871.282,I,USA,5.626946,7372.0,2019-10-01,108.762381,3660.614,8.121391,-0.001772,5345.834626,2.048684,0.109713,0.028527,0.380128,0.079826,0.044473,4.342972,0.001290
3916406,2019,4.0,ZYNGA INC,187576,41860.0,41860,0.001021,0.000473,0.0,0.019717,0.030603,0.034180,0.020470,0.004482,0.023260,0.020889,-373.907286,1386.929825,2369.385965,-962.817193,-962.344912,0.000000,0.020833,0.0,0.055921,0.0,0.204069,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.054581,0.000000,0.339425,0.0,0.270590,0.037037,0.0,0.0,0.0,0.017544,0.00000,0.718083,0.281917,0.193484,0.138889,0.0,0.861111,0.00000,0.000000,0.0,1.0,0.0,3.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,16.0,0.0,13.0,1.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,22.0,0.0,0.0,44,20191231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2019Q4,2019Q4,3365.698651,1816.280571,1279.396408,103.208523,950.042,14.483868,644.300899,-3.218024,0.000000,-3.218024,50.899033,149.682269,371.877661,371.877661,96.014816,208.726581,21.732698,444.644,5.271124,1321.659,1321.659,465.132332,871.282,I,USA,5.626946,7372.0,2019-10-01,108.762381,3660.614,8.121391,-0.001772,5345.834626,2.048684,0.109713,0.028527,0.380128,0.079826,0.044473,4.342972,0.001290

In [ ]:
df_tt.to_csv('/Users/mgor/Documents/Strategy/2YP/Data/data_merged/Merged_main/panel_aux2.csv.zip', compression='zip', index=False)

In [ ]:
df_panel.to_pickle('panel_main.pkl.gzip')

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
df=df_tt[['year','quarter','BestFitMSA','occ_arch_sum',
 'occ_art_sum',
 'occ_clean_sum',
 'occ_bus_sum',
 'occ_soc_com_sum',
 'occ_math_sum',
 'occ_constr_sum',
 'occ_educ_sum',
 'occ_farm_sum',
 'occ_food_sum',
 'occ_health_prac_sum',
 'occ_health_sup_sum',
 'occ_inst_sum',
 'occ_legal_sum',
 'occ_sci_sum',
 'occ_manage_sum',
 'occ_mil_sum',
 'occ_not_defined_sum',
 'occ_off_adm_sum',
 'occ_care_sum',
 'occ_prod_sum',
 'occ_protec_sum',
 'occ_sales_sum',
 'occ_trans_sum',
 'high_sec_educ_sum',
 'assoc_educ_sum',
 'bach_educ_sum',
 'mast_educ_sum',
 'phd_educ_sum',
 'tot_post_sum']]

In [ ]:
 'sec_accom_food_sum',
 'sec_adm_wast_sum',
 'sec_agric_sum',
 'sec_arts_sum',
 'sec_const_sum',
 'sec_educ_sum',
 'sec_finan_sum',
 'sec_health_sum',
 'sec_inf_sum',
 'sec_manage_sum',
 'sec_sum',
 'sec_mini_sum',
 'sec_not_defined_sum',
 'sec_serv_nonpub_sum',
 'sec_prof_serv_sum',
 'sec_pub_adm_sum',
 'sec_realest_sum',
 'sec_retail_sum',
 'sec_trans_sum',
 'sec_util_sum',
 'sec_whole_sum',
 'spe_skill_sum',
 'base_skill_sum',
 'softw_skill_sum',

In [7]:
aux=df.groupby(['BestFitMSA','year','quarter']).sum()

In [8]:
df2=aux.groupby(['BestFitMSA','year','quarter']).sum().groupby(['BestFitMSA']).pct_change()

In [42]:
df_test

,BestFitMSA,year,quarter,occ_arch_growth,occ_art_growth,occ_clean_growth,occ_bus_growth,occ_soc_com_growth,occ_math_growth,occ_constr_growth,occ_educ_growth,occ_farm_growth,occ_food_growth,occ_health_prac_growth,occ_health_sup_growth,occ_inst_growth,occ_legal_growth,occ_sci_growth,occ_manage_growth,occ_mil_growth,occ_not_defined_growth,occ_off_adm_growth,occ_care_growth,occ_prod_growth,occ_protec_growth,occ_sales_growth,occ_trans_growth,high_sec_educ_growth,assoc_educ_growth,bach_educ_growth,mast_educ_growth,phd_educ_growth,tot_post_sum
0,10100,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10100,2010,2.0,0.077586,-0.014943,0.008621,0.060345,0.000000,0.029310,0.008621,0.000000,0.000000,0.051724,-0.023563,0.000000,-0.024713,0.000000,0.008621,0.095977,0.000000,0.017241,-0.081609,-0.007471,-0.016092,0.000000,-0.116667,-0.072989,-0.089080,-0.049425,-0.032184,-0.016092,0.000000,2.866667
2,10100,2010,3.0,-0.031785,-0.005923,-0.008621,0.046525,0.000000,0.015728,-0.008621,0.000000,0.000000,-0.013556,-0.035470,0.000000,0.021914,0.000000,0.006646,0.030995,0.000000,0.005659,0.001711,-0.010595,-0.009608,0.000000,0.017176,-0.022177,0.014017,0.013293,-0.019216,-0.009608,0.000000,0.129310
3,10100,2010,4.0,0.029198,-0.008302,0.000000,-0.081870,0.000000,-0.082538,0.000000,0.000000,0.000000,-0.038168,-0.007634,0.000000,0.044466,0.000000,-0.015267,-0.010305,0.000000,0.014599,0.009065,-0.015267,0.004866,0.000000,0.132824,0.024332,0.158397,0.019466,0.097233,0.004866,0.000000,-0.389313
4,10100,2011,1.0,-0.055000,0.002500,0.000000,-0.005000,0.000000,-0.062500,0.020000,0.000000,0.000000,0.000000,0.060000,0.000000,0.045000,0.000000,0.020000,-0.070000,0.000000,-0.037500,0.017500,0.000000,0.027500,0.000000,-0.020000,0.057500,-0.030000,0.010000,-0.052500,-0.012500,0.000000,-0.375000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46279,na,2020,4.0,0.000689,0.001811,0.000867,0.033590,0.000666,0.006757,0.001425,0.000292,-0.000357,0.003702,0.020078,-0.000791,0.009412,0.002178,-0.002846,0.010123,-0.000027,0.005174,-0.047170,0.000461,0.000743,0.000362,-0.017067,-0.030072,-0.085840,0.006659,0.044419,-0.000441,0.001232,0.044719
46280,na,2021,1.0,0.008327,0.002045,0.002577,-0.029283,-0.000247,0.020652,0.001799,0.000114,0.001021,-0.001201,0.004276,0.001546,0.002102,-0.003388,0.001952,0.021707,-0.000008,0.001585,-0.019940,0.000054,0.006657,-0.000926,-0.011714,-0.009709,0.005810,0.000275,0.031399,0.003125,0.002052,-0.025089
46281,na,2021,2.0,0.000520,0.007933,-0.005568,-0.008540,0.000086,-0.007649,-0.000115,-0.000063,-0.000401,0.001281,-0.018017,-0.000591,-0.011300,-0.000527,-0.000693,-0.007966,-0.000094,0.002433,0.014379,0.000196,0.000757,0.001101,0.042143,-0.009304,0.052255,-0.002334,-0.025147,-0.002209,-0.002206,0.218950
46282,na,2021,3.0,0.007358,-0.006721,-0.001816,0.005926,0.000081,-0.002074,-0.000983,-0.000804,0.000667,0.003031,0.004370,0.002614,0.006503,-0.000080,0.001717,0.007486,0.000142,0.000941,-0.001737,0.000054,0.010997,-0.000219,-0.039643,0.002191,0.001071,0.005733,0.000805,0.000927,0.001705,-0.269433
46283,na,2021,4.0,-0.004981,0.006351,-0.004566,0.021491,0.001562,0.055372,-0.003382,0.005071,-0.001536,-0.019594,-0.006784,-0.006651,-0.017723,0.000393,0.000086,0.025461,-0.000172,0.006876,-0.002503,-0.005110,-0.026420,0.000455,-0.008292,-0.015403,-0.108781,-0.002822,0.118796,0.002415,-0.000114,0.822591

In [9]:
df2=df2[['tot_post_sum']]

In [10]:
###Divide post per occupation by the total number of posts per msa per quarter
df_test1=aux.iloc[:,:29].div(aux.iloc[:,29],axis=0)

In [11]:
## Difference in the proportion of job posts per occupation per MSA per quarter
df_test=df_test1.groupby(['BestFitMSA']).diff().reset_index()

In [12]:
df_test.columns = df_test.columns.str.replace("sum", "growth")

In [13]:
df_test=df_test.set_index(['BestFitMSA','year','quarter'])

In [18]:
df_test[(df_test.year==2010)&(df_test.quarter==1)]

,BestFitMSA,year,quarter,occ_arch_growth,occ_art_growth,occ_clean_growth,occ_bus_growth,occ_soc_com_growth,occ_math_growth,occ_constr_growth,occ_educ_growth,occ_farm_growth,occ_food_growth,occ_health_prac_growth,occ_health_sup_growth,occ_inst_growth,occ_legal_growth,occ_sci_growth,occ_manage_growth,occ_mil_growth,occ_not_defined_growth,occ_off_adm_growth,occ_care_growth,occ_prod_growth,occ_protec_growth,occ_sales_growth,occ_trans_growth,high_sec_educ_growth,assoc_educ_growth,bach_educ_growth,mast_educ_growth,phd_educ_growth,tot_post_sum
0,10100,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,10140,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,10180,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,10220,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,10300,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46045,78500,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46092,78700,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46140,78850,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46188,79600,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46236,na,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_test=df_test.join(df2)

In [16]:
df_test=df_test.reset_index()

In [19]:
df_test

,BestFitMSA,year,quarter,occ_arch_growth,occ_art_growth,occ_clean_growth,occ_bus_growth,occ_soc_com_growth,occ_math_growth,occ_constr_growth,occ_educ_growth,occ_farm_growth,occ_food_growth,occ_health_prac_growth,occ_health_sup_growth,occ_inst_growth,occ_legal_growth,occ_sci_growth,occ_manage_growth,occ_mil_growth,occ_not_defined_growth,occ_off_adm_growth,occ_care_growth,occ_prod_growth,occ_protec_growth,occ_sales_growth,occ_trans_growth,high_sec_educ_growth,assoc_educ_growth,bach_educ_growth,mast_educ_growth,phd_educ_growth,tot_post_sum
0,10100,2010,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10100,2010,2.0,0.077586,-0.014943,0.008621,0.060345,0.000000,0.029310,0.008621,0.000000,0.000000,0.051724,-0.023563,0.000000,-0.024713,0.000000,0.008621,0.095977,0.000000,0.017241,-0.081609,-0.007471,-0.016092,0.000000,-0.116667,-0.072989,-0.089080,-0.049425,-0.032184,-0.016092,0.000000,2.866667
2,10100,2010,3.0,-0.031785,-0.005923,-0.008621,0.046525,0.000000,0.015728,-0.008621,0.000000,0.000000,-0.013556,-0.035470,0.000000,0.021914,0.000000,0.006646,0.030995,0.000000,0.005659,0.001711,-0.010595,-0.009608,0.000000,0.017176,-0.022177,0.014017,0.013293,-0.019216,-0.009608,0.000000,0.129310
3,10100,2010,4.0,0.029198,-0.008302,0.000000,-0.081870,0.000000,-0.082538,0.000000,0.000000,0.000000,-0.038168,-0.007634,0.000000,0.044466,0.000000,-0.015267,-0.010305,0.000000,0.014599,0.009065,-0.015267,0.004866,0.000000,0.132824,0.024332,0.158397,0.019466,0.097233,0.004866,0.000000,-0.389313
4,10100,2011,1.0,-0.055000,0.002500,0.000000,-0.005000,0.000000,-0.062500,0.020000,0.000000,0.000000,0.000000,0.060000,0.000000,0.045000,0.000000,0.020000,-0.070000,0.000000,-0.037500,0.017500,0.000000,0.027500,0.000000,-0.020000,0.057500,-0.030000,0.010000,-0.052500,-0.012500,0.000000,-0.375000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46279,na,2020,4.0,0.000689,0.001811,0.000867,0.033590,0.000666,0.006757,0.001425,0.000292,-0.000357,0.003702,0.020078,-0.000791,0.009412,0.002178,-0.002846,0.010123,-0.000027,0.005174,-0.047170,0.000461,0.000743,0.000362,-0.017067,-0.030072,-0.085840,0.006659,0.044419,-0.000441,0.001232,0.044719
46280,na,2021,1.0,0.008327,0.002045,0.002577,-0.029283,-0.000247,0.020652,0.001799,0.000114,0.001021,-0.001201,0.004276,0.001546,0.002102,-0.003388,0.001952,0.021707,-0.000008,0.001585,-0.019940,0.000054,0.006657,-0.000926,-0.011714,-0.009709,0.005810,0.000275,0.031399,0.003125,0.002052,-0.025089
46281,na,2021,2.0,0.000520,0.007933,-0.005568,-0.008540,0.000086,-0.007649,-0.000115,-0.000063,-0.000401,0.001281,-0.018017,-0.000591,-0.011300,-0.000527,-0.000693,-0.007966,-0.000094,0.002433,0.014379,0.000196,0.000757,0.001101,0.042143,-0.009304,0.052255,-0.002334,-0.025147,-0.002209,-0.002206,0.218950
46282,na,2021,3.0,0.007358,-0.006721,-0.001816,0.005926,0.000081,-0.002074,-0.000983,-0.000804,0.000667,0.003031,0.004370,0.002614,0.006503,-0.000080,0.001717,0.007486,0.000142,0.000941,-0.001737,0.000054,0.010997,-0.000219,-0.039643,0.002191,0.001071,0.005733,0.000805,0.000927,0.001705,-0.269433
46283,na,2021,4.0,-0.004981,0.006351,-0.004566,0.021491,0.001562,0.055372,-0.003382,0.005071,-0.001536,-0.019594,-0.006784,-0.006651,-0.017723,0.000393,0.000086,0.025461,-0.000172,0.006876,-0.002503,-0.005110,-0.026420,0.000455,-0.008292,-0.015403,-0.108781,-0.002822,0.118796,0.002415,-0.000114,0.822591

In [20]:
df_test1=df_tt[[ 'year','quarter','BestFitMSA','employer','sec_accom_food_sum',
 'sec_adm_wast_sum',
 'sec_agric_sum',
 'sec_arts_sum',
 'sec_const_sum',
 'sec_educ_sum',
 'sec_finan_sum',
 'sec_health_sum',
 'sec_inf_sum',
 'sec_manage_sum',
 'sec_sum',
 'sec_mini_sum',
 'sec_not_defined_sum',
 'sec_serv_nonpub_sum',
 'sec_prof_serv_sum',
 'sec_pub_adm_sum',
 'sec_realest_sum',
 'sec_retail_sum',
 'sec_trans_sum',
 'sec_util_sum',
 'sec_whole_sum']]

In [21]:
df_test1=df_test1.set_index(['BestFitMSA','year','quarter','employer'])

In [22]:
df_test1=df_test1.rename(columns={ "sec_sum":'sec_manu_sum'}, errors="raise")
df_test1.columns = df_test1.columns.str.replace("_sum", "")

In [23]:
df_test1['sector'] = df_test1.idxmax(axis=1)

In [24]:
col= ['sec_adm_wast',
 'sec_agric',
 'sec_arts',
 'sec_const',
 'sec_educ',
 'sec_finan',
 'sec_health',
 'sec_inf',
 'sec_manage',
 'sec_manu',
 'sec_mini',
 'sec_not_defined',
 'sec_serv_nonpub',
 'sec_prof_serv',
 'sec_pub_adm',
 'sec_realest',
 'sec_retail',
 'sec_trans',
 'sec_util',
 'sec_whole']

In [25]:
for columns in col:
    df_test1.loc[df_test1[columns] > 0, columns]= 1

In [26]:
df_test1=df_test1.reset_index()

In [27]:
df_test1=df_test1.merge(df_test, how='left', on=['BestFitMSA','year','quarter'])

In [28]:
df_test1

,BestFitMSA,year,quarter,employer,sec_accom_food,sec_adm_wast,sec_agric,sec_arts,sec_const,sec_educ,sec_finan,sec_health,sec_inf,sec_manage,sec_manu,sec_mini,sec_not_defined,sec_serv_nonpub,sec_prof_serv,sec_pub_adm,sec_realest,sec_retail,sec_trans,sec_util,sec_whole,sector,occ_arch_growth,occ_art_growth,occ_clean_growth,occ_bus_growth,occ_soc_com_growth,occ_math_growth,occ_constr_growth,occ_educ_growth,occ_farm_growth,occ_food_growth,occ_health_prac_growth,occ_health_sup_growth,occ_inst_growth,occ_legal_growth,occ_sci_growth,occ_manage_growth,occ_mil_growth,occ_not_defined_growth,occ_off_adm_growth,occ_care_growth,occ_prod_growth,occ_protec_growth,occ_sales_growth,occ_trans_growth,high_sec_educ_growth,assoc_educ_growth,bach_educ_growth,mast_educ_growth,phd_educ_growth,tot_post_sum
0,10580,2010,1.0,1-800-FLOWERS.COM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,sec_retail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16980,2010,1.0,1-800-FLOWERS.COM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17460,2010,1.0,1-800-FLOWERS.COM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_not_defined,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,35620,2010,1.0,1-800-FLOWERS.COM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,sec_retail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11460,2010,1.0,21ST CENTURY ONCOLOGY HLDGS,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_finan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4967493,16980,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,0.007579,-0.001394,-0.001622,-0.005573,-0.000575,0.007567,-0.000781,-0.000552,-0.000151,-0.019910,0.001767,-0.000755,0.003109,-0.000572,-0.000196,-0.012077,-4.744911e-07,0.001948,-0.004408,0.001934,-0.001004,-0.000413,-0.004283,0.030365,-0.017265,0.000349,-0.005063,-0.002452,-0.001723,0.010877
4967494,21660,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,-0.004326,0.008061,-0.006752,0.001845,-0.000320,0.010822,0.000250,-0.008520,0.000630,-0.023071,0.006454,0.017720,-0.010380,0.001096,0.003927,0.000615,0.000000e+00,-0.005838,0.016058,0.007242,-0.010076,-0.003902,0.000156,-0.001689,0.016564,0.012161,0.004402,-0.007692,0.002831,-0.082128
4967495,31080,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,-0.002545,-0.001700,0.001700,-0.006503,0.000287,-0.004078,-0.000168,-0.000516,-0.000034,-0.004940,0.005816,-0.001793,-0.001377,0.000147,0.000309,-0.006360,2.157940e-05,0.001171,0.012108,0.000997,0.000256,-0.000512,-0.007004,0.014715,-0.003143,0.001076,-0.027515,-0.003408,-0.001994,0.046043
4967496,41740,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,-0.001049,-0.002051,0.001731,-0.000201,0.000336,0.000540,0.001295,0.000517,-0.000232,-0.002418,0.001280,-0.001820,-0.001134,0.000257,-0.004310,-0.008864,-3.065470e-04,0.007588,0.007960,-0.001563,0.000589,0.000363,-0.005384,0.006880,-0.014658,-0.000368,-0.036321,0.001593,-0.002110,0.123728
4967497,41860,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,0.001676,-0.004176,-0.000237,-0.008071,0.000399,0.001391,-0.000278,-0.001485,-0.000262,-0.005153,0.001211,-0.000729,0.003915,-0.001228,-0.004801,-0.027551,5.697573e-05,0.009318,0.006262,0.000113,-0.000259,0.001375,0.002588,0.025925,0.000783,-0.001134,-0.030736,0.005601,-0.003776,0.121682

In [29]:
df_test2=df_tt[[ 'year','quarter','BestFitMSA','spe_skill_mean',
 'base_skill_mean',
 'softw_skill_mean']]

In [30]:
df_test2=df_test2.groupby(['BestFitMSA','year','quarter']).mean()

In [31]:
df_test2=df_test2.groupby(['BestFitMSA']).diff().reset_index()

In [32]:
df_test2.columns = df_test2.columns.str.replace("_mean", "_growth")

In [33]:
df_test1=df_test1.merge(df_test2, how='left', on=['BestFitMSA','year','quarter'])

In [34]:
df_test1

,BestFitMSA,year,quarter,employer,sec_accom_food,sec_adm_wast,sec_agric,sec_arts,sec_const,sec_educ,sec_finan,sec_health,sec_inf,sec_manage,sec_manu,sec_mini,sec_not_defined,sec_serv_nonpub,sec_prof_serv,sec_pub_adm,sec_realest,sec_retail,sec_trans,sec_util,sec_whole,sector,occ_arch_growth,occ_art_growth,occ_clean_growth,occ_bus_growth,occ_soc_com_growth,occ_math_growth,occ_constr_growth,occ_educ_growth,occ_farm_growth,occ_food_growth,occ_health_prac_growth,occ_health_sup_growth,occ_inst_growth,occ_legal_growth,occ_sci_growth,occ_manage_growth,occ_mil_growth,occ_not_defined_growth,occ_off_adm_growth,occ_care_growth,occ_prod_growth,occ_protec_growth,occ_sales_growth,occ_trans_growth,high_sec_educ_growth,assoc_educ_growth,bach_educ_growth,mast_educ_growth,phd_educ_growth,tot_post_sum,spe_skill_growth,base_skill_growth,softw_skill_growth
0,10580,2010,1.0,1-800-FLOWERS.COM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,sec_retail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16980,2010,1.0,1-800-FLOWERS.COM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17460,2010,1.0,1-800-FLOWERS.COM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_not_defined,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,35620,2010,1.0,1-800-FLOWERS.COM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,sec_retail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11460,2010,1.0,21ST CENTURY ONCOLOGY HLDGS,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_finan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4967493,16980,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,0.007579,-0.001394,-0.001622,-0.005573,-0.000575,0.007567,-0.000781,-0.000552,-0.000151,-0.019910,0.001767,-0.000755,0.003109,-0.000572,-0.000196,-0.012077,-4.744911e-07,0.001948,-0.004408,0.001934,-0.001004,-0.000413,-0.004283,0.030365,-0.017265,0.000349,-0.005063,-0.002452,-0.001723,0.010877,0.006671,-0.006671,0.001719
4967494,21660,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,-0.004326,0.008061,-0.006752,0.001845,-0.000320,0.010822,0.000250,-0.008520,0.000630,-0.023071,0.006454,0.017720,-0.010380,0.001096,0.003927,0.000615,0.000000e+00,-0.005838,0.016058,0.007242,-0.010076,-0.003902,0.000156,-0.001689,0.016564,0.012161,0.004402,-0.007692,0.002831,-0.082128,0.002396,-0.002396,0.002799
4967495,31080,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,-0.002545,-0.001700,0.001700,-0.006503,0.000287,-0.004078,-0.000168,-0.000516,-0.000034,-0.004940,0.005816,-0.001793,-0.001377,0.000147,0.000309,-0.006360,2.157940e-05,0.001171,0.012108,0.000997,0.000256,-0.000512,-0.007004,0.014715,-0.003143,0.001076,-0.027515,-0.003408,-0.001994,0.046043,0.006052,-0.006052,0.007637
4967496,41740,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,-0.001049,-0.002051,0.001731,-0.000201,0.000336,0.000540,0.001295,0.000517,-0.000232,-0.002418,0.001280,-0.001820,-0.001134,0.000257,-0.004310,-0.008864,-3.065470e-04,0.007588,0.007960,-0.001563,0.000589,0.000363,-0.005384,0.006880,-0.014658,-0.000368,-0.036321,0.001593,-0.002110,0.123728,0.007266,-0.007266,0.004843
4967497,41860,2021,4.0,ZYNGA INC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,0.001676,-0.004176,-0.000237,-0.008071,0.000399,0.001391,-0.000278,-0.001485,-0.000262,-0.005153,0.001211,-0.000729,0.003915,-0.001228,-0.004801,-0.027551,5.697573e-05,0.009318,0.006262,0.000113,-0.000259,0.001375,0.002588,0.025925,0.000783,-0.001134,-0.030736,0.005601,-0.003776,0.121682,0.001941,-0.001941,0.003165

In [35]:
 df_tt2=df_tt.drop(['sec_accom_food_mean',
 'sec_adm_wast_mean',
 'sec_agric_mean',
 'sec_arts_mean',
 'sec_const_mean',
 'sec_educ_mean',
 'sec_finan_mean',
 'sec_health_mean',
 'sec_inf_mean',
 'sec_manage_mean',
 'sec_manu',
 'sec_mini_mean',
 'sec_not_defined_mean',
 'sec_serv_nonpub_mean',
 'sec_prof_serv_mean',
 'sec_pub_adm_mean',
 'sec_realest_mean',
 'sec_retail_mean',
 'sec_trans_mean',
 'sec_util_mean',
 'sec_whole_mean','tot_post_mean',
 'sec_accom_food_sum',
 'sec_adm_wast_sum',
 'sec_agric_sum',
 'sec_arts_sum',
 'sec_const_sum',
 'sec_educ_sum',
 'sec_finan_sum',
 'sec_health_sum',
 'sec_inf_sum',
 'sec_manage_sum',
 'sec_sum',
 'sec_mini_sum',
 'sec_not_defined_sum',
 'sec_serv_nonpub_sum',
 'sec_prof_serv_sum',
 'sec_pub_adm_sum',
 'sec_realest_sum',
 'sec_retail_sum',
 'sec_trans_sum',
 'sec_util_sum',
 'sec_whole_sum',
 'spe_skill_sum',
 'base_skill_sum',
 'softw_skill_sum'],axis=1)

In [36]:
aux=df_tt2.merge(df_test1, how='left', on=['BestFitMSA','year','quarter','employer'])

In [1]:
aux=aux.sort_values(by=['BestFitMSA','year','quarter'])

NameError: name 'aux' is not defined

In [156]:
aux

,year,quarter,employer,gvkey,MSA,BestFitMSA,full_wilzha,career_mean,work_mean,sdgs,csr,prosocial,employee,environ,hum_rig,soc_com,exp,min_wage,max_wage,min_hour_wage,max_hour_wage,occ_arch_mean,occ_art_mean,occ_clean_mean,occ_bus_mean,occ_soc_com_mean,occ_math_mean,occ_constr_mean,occ_educ_mean,occ_farm_mean,occ_food_mean,occ_health_prac_mean,occ_health_sup_mean,occ_inst_mean,occ_legal_mean,occ_sci_mean,occ_manage_mean,occ_mil_mean,occ_not_defined_mean,occ_off_adm_mean,occ_care_mean,occ_prod_mean,occ_protec_mean,occ_sales_mean,occ_trans_mean,spe_skill_mean,base_skill_mean,softw_skill_mean,high_sec_educ_mean,assoc_educ_mean,bach_educ_mean,mast_educ_mean,phd_educ_mean,occ_arch_sum,occ_art_sum,occ_clean_sum,occ_bus_sum,occ_soc_com_sum,occ_math_sum,occ_constr_sum,occ_educ_sum,occ_farm_sum,occ_food_sum,occ_health_prac_sum,occ_health_sup_sum,occ_inst_sum,occ_legal_sum,occ_sci_sum,occ_manage_sum,occ_mil_sum,occ_not_defined_sum,occ_off_adm_sum,occ_care_sum,occ_prod_sum,occ_protec_sum,occ_sales_sum,occ_trans_sum,high_sec_educ_sum,assoc_educ_sum,bach_educ_sum,mast_educ_sum,phd_educ_sum,tot_post_sum_x,datadate,indfmt,consol,popsrc,datafmt,tic,cusip,conm,curcdq,datacqtr,datafqtr,atq,ceqq,cheq,cogsq,cshoq,dlcq,dlttq,ibq,invfgq,niq,oibdpq,ppentq,revtq,saleq,xrdq,xsgaq,capxy,cogsy,oibdpy,revty,saley,xrdy,xsgay,costat,fic,prccq,sic,date,cpi,"ifelse(atq > 0, atq, NA)",logSize,roe,meq,tonbiq,mlev,rd_at,cash_at,gprofit,tang,capxq,capx_at,sec_accom_food,sec_adm_wast,sec_agric,sec_arts,sec_const,sec_educ,sec_finan,sec_health,sec_inf,sec_manage,sec_manu,sec_mini,sec_not_defined,sec_serv_nonpub,sec_prof_serv,sec_pub_adm,sec_realest,sec_retail,sec_trans,sec_util,sec_whole,sector,occ_arch_growth,occ_art_growth,occ_clean_growth,occ_bus_growth,occ_soc_com_growth,occ_math_growth,occ_constr_growth,occ_educ_growth,occ_farm_growth,occ_food_growth,occ_health_prac_growth,occ_health_sup_growth,occ_inst_growth,occ_legal_growth,occ_sci_growth,occ_manage_growth,occ_mil_growth,occ_not_defined_growth,occ_off_adm_growth,occ_care_growth,occ_prod_growth,occ_protec_growth,occ_sales_growth,occ_trans_growth,high_sec_educ_growth,assoc_educ_growth,bach_educ_growth,mast_educ_growth,phd_educ_growth,tot_post_sum_y,spe_skill_growth,base_skill_growth,softw_skill_growth
0,2010,1.0,1-800-FLOWERS.COM,122519,10580.0,10580,0.000000,0.000000,0.0,0.001852,0.003962,0.003962,0.000000,0.003962,0.000000,0.000000,3.000000,-999.0,-999.0,-999.0,-999.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.500000,0.0,0.500000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.272727,0.727273,0.272727,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2,20090930.0,INDL,C,D,STD,FLWS,68243Q106,1-800-FLOWERS.COM,USD,2009Q3,2010Q1,327.479132,138.783837,3.246017,76.757492,63.48,56.941041,69.849872,-6.178008,51.693114,-7.932405,-3.066106,57.625790,118.103975,118.103975,NaN,50.773936,2.489303,64.562,-3.066106,108.316,108.316,NaN,46.566,A,USA,3.761759,5961.0,2010-01-01,91.712409,300.339,5.791424,-0.057157,238.796476,1.305402,0.346814,NaN,0.009912,0.126257,0.175968,2.489303,0.007601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,sec_retail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,1.0,1-800-FLOWERS.COM,122519,16980.0,16980,0.000000,0.000000,0.0,0.007380,0.011070,0.011070,0.003690,0.007380,0.007380,0.000000,2.000000,-999.0,-999.0,-999.0,-999.0,0.0,1.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.736842,0.263158,0.157895,0.0,0.000000,1.000000,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1,20090930.0,INDL,C,D,STD,FLWS,68243Q106,1-800-FLOWERS.COM,USD,2009Q3,2010Q1,327.479132,138.783837,3.246017,76.757492,63.48,56.941041,69.849872,-6.178008,51.693114,-7.932405,-3.066106,57.625790,118.103975,118.103975,NaN,50.773936,2.489303,64.562,-3.066106,108.316,108.316,NaN,46.566,A,USA,3.761759,5961.0,2010-01-01,91.712409,300.339,5.791424,-0.057157,238.796476,1.305402,0.346814,NaN,0.009912,0.126257,0.175968,2.489303,0.007601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,1.0,1-800-FLOWERS.COM,122519,17460.0,17460,0.000000,0.000000,0.0,0.000000,0.021390,0.021390,0.016043,0.005348,0.016043,0.005348,2.000000,-999.0,-999.0,-999.0,-999.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,1.0,0.000000,0.0,0.0,0.000000,0.0,0.250000,0.750000,0.250000,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,20090930.0,INDL,C,D,STD,FLWS,68243Q106,1-800-FLOWERS.COM,USD,2009Q3,2010Q1,327.479132,138.783837,3.246017,76.757492,63.48,56.941041,69.849872,-6.178008,51.693114,-7.932405,-3.066106,57.625790,118.103975,118.103975,NaN,50.773936,2.489303,64.562,-3.066106,108.316,108.316,NaN,46.566,A,USA,3.761759,5961.0,2010-01-01,91.712409,300.339,5.791424,-0.057157,238.796476,1.305402,0.346814,NaN,0.009912,0.126257,0.175968,2.489303,0.007601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_not_defined,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,1.0,1-800-FLOWERS.COM,122519,35620.0,35620,0.000000,0.000137,0.0,0.000410,0.015937,0.014226,0.002046,0.009543,0.002359,0.004382,-110.115385,-999.0,-999.0,-999.0,-999.0,0.0,0.038462,0.0,0.000000,0.0,0.576923,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.230769,0.0,0.038462,0.0,0.000000,0.0,0.0,0.115385,0.0,0.713770,0.286230,0.115953,0.0,0.055556,0.888889,0.055556,0.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,8.0,1.0,0.0,14,20090930.0,INDL,C,D,STD,FLWS,68243Q106,1-800-FLOWERS.COM,USD,2009Q3,2010Q1,327.479132,138.783837,3.246017,76.757492,63.48,56.941041,69.849872,-6.178008,51.693114,-7.932405,-3.066106,57.625790,118.103975,118.103975,NaN,50.773936,2.489303,64.562,-3.066106,108.316,108.316,NaN,46.566,A,USA,3.761759,5961.0,2010-01-01,91.712409,300.339,5.791424,-0.057157,238.796476,1.305402,0.346814,NaN,0.009912,0.126257,0.175968,2.489303,0.007601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,sec_retail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,1.0,21ST CENTURY ONCOLOGY HLDGS,265008,11460.0,11460,0.000000,0.000000,0.0,0.001748,0.036620,0.036620,0.017281,0.019339,0.016972,0.011727,5.000000,-999.0,-999.0,-999.0,-999.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.5,0.000000,0.0,0.0,0.000000,0.0,0.558824,0.441176,0.088235,1.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2,20100331.0,INDL,C,D,STD,21ST10,90131G107,21ST CENTURY ONCOLOGY HLDGS,USD,2010Q1,2010Q1,NaN,NaN,NaN,109.422404,NaN,NaN,NaN,-1.969199,NaN,-1.969199,28.824889,NaN,146.690074,146.690074,0.000000,17.511262,NaN,92.037,28.824889,134.533,134.533,0.000000,16.060,I,USA,NaN,8090.0,2010-01-01,91.712409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_finan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5044063,2021,4.0,ZYNGA INC,187576,16980.0,16980,0.002137,0.000000,0.0,0.020211,0.039343,0.045070,0.033266,0.005905,0.032431,0.026407,-162.400000,-999.0,-999.0,-999.0,-999.0,0.0,0.400000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.066667,0.133333,0.0,0.000000,0.0,0.233333,0.0,0.0,0.166667,0.0,0.675845,0.324155,0.181202,0.0,0.333333,0.666667,0.000000,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,8,20211231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2021Q4,2021Q4,5413.416748,2649.202154,1118.625801,139.076550,1130.50,14.557459,1257.560147,-57.293391,0.000000,-57.293391,89.473038,99.348273,592.088466,592.088466,129.314505,339.248388,10.641417,776.000,403.777943,2800.500,2800.500,464.731982,1550.200,I,USA,5.448406,7372.0,2021-10-01,117.465554,6358.900,8.596636,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,0.007579,-0.001394,-0.001622,-0.005573,-0.000575,0.007567,-0.000781,-0.000552,-0.000151,-0.019910,0.001767,-0.000755,0.003109,-0.000572,-0.000196,-0.012077,-4.744911e-07,0.001948,-0.004408,0.001934,-0.001004,-0.000413,-0.004283,0.030365,-0.017265,0.000349,-0.005063,-0.002452,-0.001723,0.010877,0.006671,-0.006671,0.001719
5044064,2021,4.0,ZYNGA INC,187576,21660.0,21660,0.000000,0.000000,0.0,0.022951,0.045902,0.052459,0.039344,0.006557,0.029508,0.022951,1.000000,-999.0,-999.0,-999.0,-999.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.533333,0.466667,0.066667,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,20211231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2021Q4,2021Q4,5413.416748,2649.202154,1118.625801,139.076550,1130.50,14.557459,1257.560147,-57.293391,0.000000,-57.293391,89.473038,99.348273,592.088466,592.088466,129.314505,339.248388,10.641417,776.000,403.777943,2800.500,2800.500,464.731982,1550.200,I,USA,5.448406,7372.0,2021-10-01,117.465554,6358.900,8.596636,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,-0.004326,0.008061,-0.006752,0.001845,-0.000320,0.010822,0.000250,-0.008520,0.000630,-0.023071,0.006454,0.017720,-0.010380,0.001096,0.003927,0.000615,0.000000e+00,-0.005838,0.016058,0.007242,-0.010076,-0.003902,0.000156,-0.001689,0.016564,0.012161,0.004402,-0.007692,0.002831,-0.082128,0.002396,-0.002396,0.002799
5044065,2021,4.0,ZYNGA INC,187576,31080.0,31080,0.002110,0.000000,0.0,0.023207,0.037975,0.044304,0.031646,0.004219,0.033755,0.027426,3.000000,-999.0,-999.0,-999.0,-999.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,1.000000,0.0,0.777778,0.222222,0.000000,0.0,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1,20211231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2021Q4,2021Q4,5413.416748,2649.202154,1118.625801,139.076550,1130.50,14.557459,1257.560147,-57.293391,0.000000,-57.293391,89.473038,99.348273,592.088466,592.088466,129.314505,339.248388,10.641417,776.000,403.777943,2800.500,2800.500,464.731982,1550.200,I,USA,5.448406,7372.0,2021-10-01,117.465554,6358.900,8.596636,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,-0.002545,-0.001700,0.001700,-0.006503,0.000287,-0.004078,-0.000168,-0.000516,-0.000034,-0.004940,0.005816,-0.001793,-0.001377,0.000147,0.000309,-0.006360,2.157940e-05,0.001171,0.012108,0.000997,0.000256,-0.000512,-0.007004,0.014715,-0.003143,0.001076,-0.027515,-0.003408,-0.001994,0.046043,0.006052,-0.006052,0.007637
5044066,2021,4.0,ZYNGA INC,187576,41740.0,41740,0.000000,0.000000,0.0,0.022876,0.045752,0.052288,0.039216,0.006536,0.029412,0.022876,1.000000,-999.0,-999.0,-999.0,-999.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.533333,0.466667,0.066667,0.0,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,20211231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2021Q4,2021Q4,5413.416748,2649.202154,1118.625801,139.076550,1130.50,14.557459,1257.560147,-57.293391,0.000000,-57.293391,89.473038,99.348273,592.088466,592.088466,129.314505,339.248388,10.641417,776.000,403.777943,2800.500,2800.500,464.731982,1550.200,I,USA,5.448406,7372.0,2021-10-01,117.465554,6358.900,8.596636,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,-0.001049,-0.002051,0.001731,-0.000201,0.000336,0.000540,0.001295,0.000517,-0.000232,-0.002418,0.001280,-0.001820,-0.001134,0.000257,-0.004310,-0.008864,-3.065470e-04,0.007588,0.007960,-0.001563,0.000589,0.000363,-0.005384,0.006880,-0.014658,-0.000368,-0.036321,0.001593,-0.002110,0.123728,0.007266,-0.007266,0.004843
5044067,2021,4.0,ZYNGA INC,187576,41860.0,41860,0.001544,0.001907,0.0,0.025633,0.044486,0.051142,0.035230,0.008819,0.039457,0.027031,-259.095238,-999.0,-999.0,-999.0,-999.0,0.0,0.047619,0.0,0.047619,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.142857,0.0,0.166667,0.5,0.000000,0.0,0.0,0.095238,0.0,0.430959,0.569041,0.083893,0.0,0.000000,1.000000,0.000000,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,4.0,0.0,0.0,10,20211231.0,INDL,C,D,STD,ZNGA,98986T108,ZYNGA INC,USD,2021Q4,2021Q4,5413.416748,2649.202154,1118.625801,139.076550,1130.50,14.557459,1257.560147,-57.293391,0.000000,-57.293391,89.473038,99.348273,592.088466,592.088466,129.314505,339.248388,10.641417,776.000,403.777943,2800.500,2800.500,464.731982,1550.200,I,USA,5.448406,7372.0,2021-10-01,117.465554,6358.900,8.596636,-0.021627,6159.422676,1.648430,0.171178,0.023888,0.206640,0.083683,0.018352,4.741227,0.000876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sec_manu,0.001676,-0.004176,-0.000237,-0.008071,0.000399,0.001391,-0.000278,-0.001485,-0.000262,-0.005153,0.001211,-0.000729,0.003915,-0.001228,-0.004801,-0.027551,5.697573e-05,0.009318,0.006262,0.000113,-0.000259,0.001375,0.002588,0.025925,0.000783,-0.001134,-0.030736,0.005601,-0.003776,0.121682,0.001941,-0.001941,0.003165

In [37]:
aux.to_csv('/Users/mgor/Documents/Strategy/2YP/Data/data_merged/Merged_main/panel_mid.csv.zip', compression='zip', index=False)

In [6]:
df_unem=pd.read_table('/Users/mgor/Documents/Strategy/2YP/Data/data_csv/Labor/unemp.csv', delimiter=',', header=0)
df_unem=df_unem.dropna(how='all')
df_unem=df_unem.rename(columns={"Year": "year", "Month":"month", "Area FIPS Code":"BestFitMSA"}, errors="raise")

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3331: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [9]:
len(df_unem['ST FIPS Code'].unique())

52

In [ ]:
df_unem.loc[df_unem['month'] < 4, 'quarter'] = 1
df_unem.loc[(df_unem['month'] > 3) & (df_unem['month'] < 7), 'quarter'] = 2
df_unem.loc[(df_unem['month'] > 6) & (df_unem['month'] < 10), 'quarter'] = 3
df_unem.loc[(df_unem['month'] > 9) & (df_unem['month'] < 13), 'quarter'] = 4

In [ ]:
df_unem=df_unem[(df_unem['Unemployment Rate'] !='(n)') ]

In [ ]:
df_unem['Unemployment Rate'] = df_unem['Unemployment Rate'].astype(float, errors = 'raise')
df_unem['BestFitMSA'] = df_unem['BestFitMSA'].astype(object, errors = 'raise')

In [ ]:
unem=df_unem.groupby(['year','quarter','BestFitMSA']).mean().reset_index()

In [ ]:
aux.BestFitMSA=aux.BestFitMSA.replace({'na': -999})

In [ ]:
aux['BestFitMSA'] = aux['BestFitMSA'].astype(int, errors = 'raise')

In [ ]:
aux=aux.merge(unem, how='left', on=['year', 'quarter', 'BestFitMSA'], indicator=True)

In [2]:
df_tt= pd.read_table('/Volumes/TOSHIBA EXT/final_variables/mainfull01.csv.zip', delimiter=',', header=0)

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3331: DtypeWarning: Columns (22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,45,46,47,48,49,50,53,54,55,57,60,61,68,69,70,71) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
df_tt

,Unnamed: 0,BGTJobId,JobReferenceID,JobDate_x,IsDuplicate,IsDuplicateOf,length,ComWord,Freq,Rel_Freq,...,sector_Utilities,sector_Wholesale Trade,IsSpecialized,IsBaseline,IsSoftware,deg_12,deg_13,deg_16,deg_18,deg_21
0,195522,39154091160,NaN,2022-01-01,False,NaN,438,training,18,0.041096,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,195523,39154091177,NaN,2022-01-01,False,NaN,452,state,9,0.019912,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,195524,39154091192,21968,2022-01-01,False,NaN,409,hospital,10,0.024450,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,195525,39154091211,NaN,2022-01-01,False,NaN,617,must,15,0.024311,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,195526,39154091226,NaN,2022-01-01,False,NaN,334,gat,6,0.017964,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981555,125201,38934941608,NaN,2021-01-20,False,NaN,402,brightree,6,0.014925,...,0,0,0.428571,0.571429,0.000000,0.0,1.0,0.0,0.0,0.0
981556,125202,38934941591,NaN,2021-01-20,False,NaN,280,nvr,8,0.028571,...,0,0,0.500000,0.500000,0.100000,NaN,NaN,NaN,NaN,NaN
981557,125203,38934941606,NaN,2021-01-20,False,NaN,528,marketing,11,0.020833,...,0,0,0.700000,0.300000,0.000000,0.0,0.0,1.0,0.0,0.0
981558,125204,38934941582,NaN,2021-01-20,False,NaN,702,systems,17,0.024217,...,0,0,0.666667,0.333333,0.466667,1.0,0.0,0.0,0.0,0.0
981559,125205,38934941619,NaN,2021-01-20,False,NaN,605,methodist,13,0.021488,...,0,0,1.000000,0.000000,0.333333,NaN,NaN,NaN,NaN,NaN

In [3]:
import pandas as pd

df_aux= pd.read_table('/Users/mgor/Documents/Strategy/2YP/Data/data_raw/Main/Skills_2021-12.zip', encoding='latin')

In [7]:
pd.set_option('display.max_rows', None)

In [10]:
df_aux[500:700]

,BGTJobId,JobDate,Skill,SkillCluster,SkillClusterFamily,IsSpecialized,IsBaseline,IsSoftware,Salary
500,39134467921,2021-11-30,Organizational Skills,na,na,0,1,0,-999
501,39134467921,2021-11-30,Assessment Data,na,na,1,0,0,-999
502,39134467921,2021-11-30,Patient Safety,Medical Support,Health Care,1,0,0,-999
503,39134467921,2021-11-30,Peer Review,Peer Review,Education and Training,1,0,0,-999
504,39134467923,2021-11-30,Building Effective Relationships,na,na,0,1,0,-999
505,39134467923,2021-11-30,Organizational Skills,na,na,0,1,0,-999
506,39134467923,2021-11-30,Information Systems,Management Information System (MIS),Information Technology,1,0,0,-999
507,39134467923,2021-11-30,Specimen Collection,Blood Collection,Health Care,1,0,0,-999
508,39134467923,2021-11-30,Cleaning,na,na,1,0,0,-999
509,39134467923,2021-11-30,Medical Technology,Medical Research,Health Care,1,0,0,-999
510,39134467923,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
511,39134467923,2021-11-30,Laboratory Equipment,Laboratory Research,Science and Research,1,0,0,-999
512,39134467923,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
513,39134467923,2021-11-30,Specimen Documentation,na,na,1,0,0,-999
514,39134467923,2021-11-30,Patient Care,Basic Patient Care,Health Care,1,0,0,-999
515,39134467923,2021-11-30,Pathology,Pathology,Health Care,1,0,0,-999
516,39134467923,2021-11-30,Phlebotomy,Blood Collection,Health Care,1,0,0,-999
517,39134467923,2021-11-30,Scheduling,Scheduling,Administration,1,0,0,-999
518,39134467923,2021-11-30,Quality Assurance and Control,Quality Assurance and Control,Business,1,0,0,-999
519,39134467923,2021-11-30,Communication Skills,na,na,0,1,0,-999
520,39134467923,2021-11-30,Specimen Processing,na,na,1,0,0,-999
521,39134467923,2021-11-30,Work Area Maintenance,na,na,0,1,0,-999
522,39134467923,2021-11-30,Infection Control,Medical Support,Health Care,1,0,0,-999
523,39134467923,2021-11-30,Customer Billing,Billing and Invoicing,Finance,1,0,0,-999
524,39134467924,2021-11-30,Ambulatory Care,Basic Patient Care,Health Care,1,0,0,-999
525,39134467924,2021-11-30,Patient Care,Basic Patient Care,Health Care,1,0,0,-999
526,39134467924,2021-11-30,Scheduling,Scheduling,Administration,1,0,0,-999
527,39134467924,2021-11-30,Nurse Management,Health Care Procedure and Regulation,Health Care,1,0,0,-999
528,39134467924,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
529,39134467924,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
530,39134467924,2021-11-30,Patient Assistance,Basic Patient Care,Health Care,1,0,0,-999
531,39134467924,2021-11-30,Patient/Family Education and Instruction,Patient Education and Support,Health Care,1,0,0,-999
532,39134467924,2021-11-30,Office Management,Office Management,Administration,1,0,0,-999
533,39134467939,2021-11-30,Problem Solving,na,na,0,1,0,-999
534,39134467939,2021-11-30,Change Management,Business Management,Business,1,0,0,-999
535,39134467939,2021-11-30,Teamwork / Collaboration,na,na,1,0,0,-999
536,39134467939,2021-11-30,Predictive Models,Data Science,Analysis,1,0,0,-999
537,39134467939,2021-11-30,Financial Modeling,Financial Analysis,Finance,1,0,0,-999
538,39134467939,2021-11-30,Financial Accounting,Financial Accounting,Finance,1,0,0,-999
539,39134467939,2021-11-30,Financial Reporting,Financial Reporting,Finance,1,0,0,-999
540,39134467939,2021-11-30,Business Development,Business Development,Sales,1,0,0,-999
541,39134467939,2021-11-30,Building Effective Relationships,na,na,0,1,0,-999
542,39134467939,2021-11-30,Performance Appraisals,Performance Management,Business,1,0,0,-999
543,39134467939,2021-11-30,Business Process,Business Process and Analysis,Business,1,0,0,-999
544,39134467939,2021-11-30,Corporate Accounting,Corporate Accounting,Finance,1,0,0,-999
545,39134467939,2021-11-30,General Ledger,General Accounting,Finance,1,0,0,-999
546,39134467939,2021-11-30,Statistical Reporting,na,na,1,0,0,-999
547,39134467939,2021-11-30,External Auditing,Auditing,Finance,1,0,0,-999
548,39134467939,2021-11-30,Fixed Assets,General Accounting,Finance,1,0,0,-999
549,39134467939,2021-11-30,Financial Analysis,Financial Analysis,Finance,1,0,0,-999
550,39134467939,2021-11-30,Generally Accepted Accounting Principles (GAAP),General Accounting,Finance,1,0,0,-999
551,39134467939,2021-11-30,Information gathering,na,na,1,0,0,-999
552,39134467939,2021-11-30,Business Planning,Business Strategy,Business,1,0,0,-999
553,39134467939,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
554,39134467939,2021-11-30,Key Performance Indicators (KPIs),Key Performance Indicators,Business,1,0,0,-999
555,39134467939,2021-11-30,Financial Consulting,Financial Advisement,Finance,1,0,0,-999
556,39134467939,2021-11-30,Decision Making,na,na,0,1,0,-999
557,39134467939,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
558,39134467939,2021-11-30,Planning,na,na,0,1,0,-999
559,39134467939,2021-11-30,Financial Statements,Financial Reporting,Finance,1,0,0,-999
560,39134467939,2021-11-30,Scheduling,Scheduling,Administration,1,0,0,-999
561,39134467939,2021-11-30,Business Administration,Business Management,Business,1,0,0,-999
562,39134467939,2021-11-30,Process Improvement,Process Improvement,Business,1,0,0,-999
563,39134467939,2021-11-30,Performance Analysis,Performance Management,Business,1,0,0,-999
564,39134467939,2021-11-30,Cost Accounting,Cost Accounting,Finance,1,0,0,-999
565,39134467939,2021-11-30,Decision Support,Business Process and Analysis,Business,1,0,0,-999
566,39134467939,2021-11-30,Computer Literacy,na,na,0,1,0,-999
567,39134467939,2021-11-30,Budgeting,Budget Management,Finance,1,0,0,-999
568,39134467939,2021-11-30,Accounting,General Accounting,Finance,1,0,0,-999
569,39134467939,2021-11-30,Public Accounting,General Accounting,Finance,1,0,0,-999
570,39134467939,2021-11-30,Spreadsheets,Microsoft Office and Productivity Tools,Information Technology,1,0,0,-999
571,39134467939,2021-11-30,Troubleshooting,na,na,0,1,0,-999
572,39134467939,2021-11-30,Strategic Development,Business Strategy,Business,1,0,0,-999
573,39134467939,2021-11-30,Payables,Accounts Payable and Receivable,Finance,1,0,0,-999
574,39134467939,2021-11-30,Communication Skills,na,na,0,1,0,-999
575,39134467939,2021-11-30,Strategic Planning,Business Strategy,Business,1,0,0,-999
576,39134467939,2021-11-30,Project Management,Project Management,Business,1,0,0,-999
577,39134467943,2021-11-30,Work Area Maintenance,na,na,0,1,0,-999
578,39134467943,2021-11-30,Neonatal Intensive Care Unit (NICU),Pediatrics,Health Care,1,0,0,-999
579,39134467943,2021-11-30,Acute Care,Medical Support,Health Care,1,0,0,-999
580,39134467943,2021-11-30,Treatment Planning,General Medicine,Health Care,1,0,0,-999
581,39134467943,2021-11-30,Problem Identification,Business Process and Analysis,Business,1,0,0,-999
582,39134467943,2021-11-30,Medication Administration,Medical Support,Health Care,1,0,0,-999
583,39134467943,2021-11-30,Patient Care,Basic Patient Care,Health Care,1,0,0,-999
584,39134467943,2021-11-30,Staff Development,People Management,Business,1,0,0,-999
585,39134467943,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
586,39134467943,2021-11-30,Mentoring,na,na,0,1,0,-999
587,39134467943,2021-11-30,Advanced Cardiac Life Support (ACLS),Emergency and Intensive Care,Health Care,1,0,0,-999
588,39134467943,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
589,39134467943,2021-11-30,Neonatal Intensive Care,Pediatrics,Health Care,1,0,0,-999
590,39134467943,2021-11-30,Peer Review,Peer Review,Education and Training,1,0,0,-999
591,39134467943,2021-11-30,Organizational Skills,na,na,0,1,0,-999
592,39134467943,2021-11-30,Patient Safety,Medical Support,Health Care,1,0,0,-999
593,39134467957,2021-11-30,Secure Shell,Scripting,Information Technology,1,0,0,-999
594,39134467957,2021-11-30,Teamwork / Collaboration,na,na,1,0,0,-999
595,39134467957,2021-11-30,Organizational Skills,na,na,0,1,0,-999
596,39134467957,2021-11-30,Normal Saline,na,na,1,0,0,-999
597,39134467957,2021-11-30,Medical Triage,General Medical Tests and Procedures,Health Care,1,0,0,-999
598,39134467957,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
599,39134467957,2021-11-30,Advanced Cardiac Life Support (ACLS),Emergency and Intensive Care,Health Care,1,0,0,-999
600,39134467957,2021-11-30,Operations Management,Operations Management,Business,1,0,0,-999
601,39134467957,2021-11-30,Electrocardiogram (EKG / ECG),Cardiology,Health Care,1,0,0,-999
602,39134467957,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
603,39134467957,2021-11-30,Splint Application,First Aid,Health Care,1,0,0,-999
604,39134467957,2021-11-30,Acute Care,Medical Support,Health Care,1,0,0,-999
605,39134467957,2021-11-30,Patient Care,Basic Patient Care,Health Care,1,0,0,-999
606,39134467957,2021-11-30,Trauma,Emergency and Intensive Care,Health Care,1,0,0,-999
607,39134467957,2021-11-30,Clinical Experience,Medical Support,Health Care,1,0,0,-999
608,39134467977,2021-11-30,Scheduling,Scheduling,Administration,1,0,0,-999
609,39134467977,2021-11-30,Front Office,Office Management,Administration,1,0,0,-999
610,39134467977,2021-11-30,Customer Billing,Billing and Invoicing,Finance,1,0,0,-999
611,39134467977,2021-11-30,Nurse Management,Health Care Procedure and Regulation,Health Care,1,0,0,-999
612,39134467977,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
613,39134467977,2021-11-30,Medical Office Experience,Health Care Procedure and Regulation,Health Care,1,0,0,-999
614,39134467977,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
615,39134467977,2021-11-30,Interaction with Patients / Medical Personnel,Basic Patient Care,Health Care,1,0,0,-999
616,39134467977,2021-11-30,Telephone Skills,na,na,0,1,0,-999
617,39134467977,2021-11-30,Appointment Setting,Administrative Support,Administration,1,0,0,-999
618,39134467977,2021-11-30,Cardiology,Cardiology,Health Care,1,0,0,-999
619,39134467977,2021-11-30,Office Management,Office Management,Administration,1,0,0,-999
620,39134467982,2021-11-30,Teamwork / Collaboration,na,na,1,0,0,-999
621,39134467982,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
622,39134467982,2021-11-30,Standards Compliance,na,na,1,0,0,-999
623,39134467982,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
624,39134467982,2021-11-30,Strategic Planning,Business Strategy,Business,1,0,0,-999
625,39134467982,2021-11-30,Data Collection,Data Techniques,Analysis,1,0,0,-999
626,39134467982,2021-11-30,Scheduling,Scheduling,Administration,1,0,0,-999
627,39134467982,2021-11-30,Patient Care,Basic Patient Care,Health Care,1,0,0,-999
628,39134467982,2021-11-30,Budgeting,Budget Management,Finance,1,0,0,-999
629,39134467989,2021-11-30,Patient Care,Basic Patient Care,Health Care,1,0,0,-999
630,39134467989,2021-11-30,Acute Care,Medical Support,Health Care,1,0,0,-999
631,39134467989,2021-11-30,Treatment Planning,General Medicine,Health Care,1,0,0,-999
632,39134467989,2021-11-30,Medication Administration,Medical Support,Health Care,1,0,0,-999
633,39134467989,2021-11-30,Problem Identification,Business Process and Analysis,Business,1,0,0,-999
634,39134467989,2021-11-30,Work Area Maintenance,na,na,0,1,0,-999
635,39134467989,2021-11-30,Neonatal Intensive Care Unit (NICU),Pediatrics,Health Care,1,0,0,-999
636,39134467989,2021-11-30,Staff Development,People Management,Business,1,0,0,-999
637,39134467989,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
638,39134467989,2021-11-30,Mentoring,na,na,0,1,0,-999
639,39134467989,2021-11-30,Advanced Cardiac Life Support (ACLS),Emergency and Intensive Care,Health Care,1,0,0,-999
640,39134467989,2021-11-30,Neonatal Intensive Care,Pediatrics,Health Care,1,0,0,-999
641,39134467989,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
642,39134467989,2021-11-30,Organizational Skills,na,na,0,1,0,-999
643,39134467989,2021-11-30,Patient Safety,Medical Support,Health Care,1,0,0,-999
644,39134467989,2021-11-30,Peer Review,Peer Review,Education and Training,1,0,0,-999
645,39134467999,2021-11-30,Supervisory Skills,People Management,Business,1,0,0,-999
646,39134467999,2021-11-30,Telecommunications,Telecommunications,Information Technology,1,0,0,-999
647,39134467999,2021-11-30,Repair,na,na,1,0,0,-999
648,39134467999,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
649,39134467999,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
650,39134467999,2021-11-30,Budgeting,Budget Management,Finance,1,0,0,-999
651,39134467999,2021-11-30,Computer Literacy,na,na,0,1,0,-999
652,39134467999,2021-11-30,Policy Implementation,Business Management,Business,1,0,0,-999
653,39134467999,2021-11-30,Staff Management,People Management,Business,1,0,0,-999
654,39134468002,2021-11-30,Cancer knowledge,Oncology,Health Care,1,0,0,-999
655,39134468002,2021-11-30,Oncology,Oncology,Health Care,1,0,0,-999
656,39134468004,2021-11-30,Organizational Skills,na,na,0,1,0,-999
657,39134468004,2021-11-30,Patient Safety,Medical Support,Health Care,1,0,0,-999
658,39134468004,2021-11-30,Assessment Data,na,na,1,0,0,-999
659,39134468004,2021-11-30,Peer Review,Peer Review,Education and Training,1,0,0,-999
660,39134468004,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
661,39134468004,2021-11-30,Staff Development,People Management,Business,1,0,0,-999
662,39134468004,2021-11-30,Mentoring,na,na,0,1,0,-999
663,39134468004,2021-11-30,Advanced Cardiac Life Support (ACLS),Emergency and Intensive Care,Health Care,1,0,0,-999
664,39134468004,2021-11-30,Neonatal Intensive Care,Pediatrics,Health Care,1,0,0,-999
665,39134468004,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
666,39134468004,2021-11-30,Patient Care,Basic Patient Care,Health Care,1,0,0,-999
667,39134468004,2021-11-30,Medication Administration,Medical Support,Health Care,1,0,0,-999
668,39134468004,2021-11-30,Problem Identification,Business Process and Analysis,Business,1,0,0,-999
669,39134468004,2021-11-30,Treatment Planning,General Medicine,Health Care,1,0,0,-999
670,39134468004,2021-11-30,Caregiving,Basic Living Activities Support,Health Care,1,0,0,-999
671,39134468004,2021-11-30,Neonatal Intensive Care Unit (NICU),Pediatrics,Health Care,1,0,0,-999
672,39134468004,2021-11-30,Work Area Maintenance,na,na,0,1,0,-999
673,39134468007,2021-11-30,Work Area Maintenance,na,na,0,1,0,-999
674,39134468007,2021-11-30,Neonatal Intensive Care Unit (NICU),Pediatrics,Health Care,1,0,0,-999
675,39134468007,2021-11-30,Caregiving,Basic Living Activities Support,Health Care,1,0,0,-999
676,39134468007,2021-11-30,Treatment Planning,General Medicine,Health Care,1,0,0,-999
677,39134468007,2021-11-30,Patient Care,Basic Patient Care,Health Care,1,0,0,-999
678,39134468007,2021-11-30,Problem Identification,Business Process and Analysis,Business,1,0,0,-999
679,39134468007,2021-11-30,Medication Administration,Medical Support,Health Care,1,0,0,-999
680,39134468007,2021-11-30,Trauma,Emergency and Intensive Care,Health Care,1,0,0,-999
681,39134468007,2021-11-30,Mentoring,na,na,0,1,0,-999
682,39134468007,2021-11-30,Advanced Cardiac Life Support (ACLS),Emergency and Intensive Care,Health Care,1,0,0,-999
683,39134468007,2021-11-30,Americans with Disabilities Act (ADA),Labor Compliance,Legal,1,0,0,-999
684,39134468007,2021-11-30,Neonatal Intensive Care,Pediatrics,Health Care,1,0,0,-999
685,39134468007,2021-11-30,Staff Development,People Management,Business,1,0,0,-999
686,39134468007,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
687,39134468007,2021-11-30,Peer Review,Peer Review,Education and Training,1,0,0,-999
688,39134468007,2021-11-30,Organizational Skills,na,na,0,1,0,-999
689,39134468007,2021-11-30,Assessment Data,na,na,1,0,0,-999
690,39134468007,2021-11-30,Patient Safety,Medical Support,Health Care,1,0,0,-999
691,39134468014,2021-11-30,Organizational Skills,na,na,0,1,0,-999
692,39134468014,2021-11-30,Patient Safety,Medical Support,Health Care,1,0,0,-999
693,39134468014,2021-11-30,Assessment Data,na,na,1,0,0,-999
694,39134468014,2021-11-30,Peer Review,Peer Review,Education and Training,1,0,0,-999
695,39134468014,2021-11-30,Post Anesthesia Care Unit (PACU),Anesthesiology,Health Care,1,0,0,-999
696,39134468014,2021-11-30,Staff Development,People Management,Business,1,0,0,-999
697,39134468014,2021-11-30,Family Medical Leave Act (FMLA),Labor Compliance,Legal,1,0,0,-999
698,39134468014,2021-11-30,Mentoring,na,na,0,1,0,-999
699,39134468014,2021-11-30,Advanced Cardiac Life Support (ACLS),Emergency and Intensive Care,Health Care,1,0,0,-999